import type {
  ActionCategory,
  ActivityItem,
  AiFinding,
  Announcement,
  AssetFacilitiesSnapshot,
  ClinicGroup,
  ClinicHealthProfile,
  CommandAction,
  ComplianceItem,
  DashboardSectionLayout,
  DigitalSecuritySnapshot,
  ExecutiveItem,
  FinanceSnapshot,
  IncidentRecord,
  PositiveMessage,
  StaffingSnapshot,
  TaskDeliverySummary,
  TrendCard,
} from "./types";
import { healthBand, overallFromAreas } from "./utils";

const AREAS: ActionCategory[] = [
  "Clinic Operations",
  "Staffing",
  "Compliance",
  "Finance & Pay",
  "Incidents",
  "Tasks & Checklists",
  "Assets & Facilities",
  "Digital & Security",
];

function areasFrom(scores: Array<number | null>) {
  return AREAS.map((area, i) => ({ area, score: scores[i] ?? null }));
}

function profile(
  locationId: string,
  scores: Array<number | null>,
  extras: Partial<ClinicHealthProfile>
): ClinicHealthProfile {
  const overall = overallFromAreas(scores);
  const yesterdayAreas = areasFrom(
    scores.map((s) => (s === null ? null : Math.max(0, Math.min(100, s + (s >= 80 ? -1 : 2)))))
  );
  const yesterdayScore = overallFromAreas(yesterdayAreas.map((a) => a.score));
  return {
    locationId,
    overallScore: overall,
    yesterdayScore,
    band: healthBand(overall),
    emergencyStatus: false,
    openingStatus: "Open",
    openingChecklist: "Complete",
    staffingStatus: "Covered",
    roomsStatus: "Ready",
    systemsStatus: "Healthy",
    urgentIssues: 0,
    overdueWork: 0,
    manager: "Practice Manager",
    lastUpdate: "2026-07-16T08:42:00",
    areas: areasFrom(scores),
    yesterdayAreas,
    trend: "No change",
    strongest: "Clinic Operations",
    weakest: "Staffing",
    positiveFactors: ["Opening checklist complete", "Systems available"],
    attentionItems: [],
    missingInfo: scores.some((s) => s === null) ? ["One or more area scores unavailable"] : [],
    ...extras,
  };
}

export const CLINIC_HEALTH: ClinicHealthProfile[] = [
  profile("loc_baldhills", [92, 78, 88, 91, 85, 90, 87, 93], {
    manager: "Neil Udukala",
    urgentIssues: 1,
    overdueWork: 2,
    staffingStatus: "Gap",
    trend: "Declined",
    weakest: "Staffing",
    strongest: "Digital & Security",
  }),
  profile("loc_cannonhill", [86, 84, 72, 88, 80, 82, 79, 90], {
    manager: "Sarah Chen",
    openingChecklist: "Late",
    urgentIssues: 2,
    overdueWork: 3,
    band: "Attention Required",
    trend: "Declined",
    weakest: "Compliance",
  }),
  profile("loc_woolloongabba", [94, 91, 93, 90, 92, 95, 91, 94], {
    manager: "Priya Nair",
    trend: "Improved",
    strongest: "Tasks & Checklists",
  }),
  profile("loc_eightmile", [81, 76, 84, 82, 78, 80, 77, 85], {
    manager: "Tom Bradley",
    staffingStatus: "Gap",
    overdueWork: 4,
    trend: "No change",
  }),
  profile("loc_chapelhill", [88, 90, 86, 87, 89, 88, 84, 91], {
    manager: "Helen Park",
    trend: "Improved",
  }),
  profile("loc_indooroopilly", [74, 68, 70, 76, 65, 72, 71, 80], {
    manager: "James Okonkwo",
    urgentIssues: 3,
    overdueWork: 5,
    staffingStatus: "Critical gap",
    systemsStatus: "Degraded",
    trend: "Declined",
    weakest: "Incidents",
  }),
  profile("loc_forestlake", [90, 88, 91, 89, 90, 92, 88, 93], {
    manager: "Amelia Scott",
    trend: "Improved",
  }),
  profile("loc_lawnton", [83, 80, null, 85, 82, 84, 81, 86], {
    manager: "Chris Nguyen",
    overdueWork: 1,
    weakest: "Compliance",
    strongest: "Digital & Security",
  }),
  profile("loc_beachmere", [60, 58, 62, 64, 55, 61, 59, 70], {
    manager: "Laura Dias",
    openingStatus: "Temporarily Closed",
    openingChecklist: "Not started",
    urgentIssues: 4,
    overdueWork: 6,
    emergencyStatus: true,
    systemsStatus: "Outage",
    roomsStatus: "Blocked",
    staffingStatus: "Critical gap",
    trend: "Declined",
  }),
];

export const CLINIC_GROUPS: ClinicGroup[] = [
  { id: "grp_north", name: "North corridor", locationIds: ["loc_baldhills", "loc_lawnton", "loc_beachmere"] },
  { id: "grp_east", name: "East corridor", locationIds: ["loc_cannonhill", "loc_woolloongabba"] },
  { id: "grp_west", name: "West corridor", locationIds: ["loc_indooroopilly", "loc_chapelhill", "loc_forestlake"] },
];

export const ANNOUNCEMENTS: Announcement[] = [
  {
    id: "ann-em-1",
    title: "Beachmere clinic temporary closure — utilities fault",
    type: "Emergency",
    message:
      "Beachmere is temporarily closed due to a critical utilities fault. Patients are being redirected. Owner acknowledgement required.",
    clinics: ["loc_beachmere"],
    roles: ["Owner / Director", "Practice Manager", "Reception"],
    publishAt: "2026-07-16T06:15:00",
    requireAck: true,
    channels: ["Dashboard", "Email", "SMS"],
    attachments: 1,
    relatedActionId: "ACT-2026-001284",
    acknowledged: false,
    readership: { read: 42, total: 68 },
    delivery: { delivered: 66, total: 68 },
    acknowledgements: { acked: 18, total: 24 },
  },
  {
    id: "ann-1",
    title: "July compliance pack due Friday",
    type: "Normal",
    message: "Clinic managers must submit July compliance evidence packs by Friday 17:00.",
    clinics: ["all"],
    roles: ["Practice Manager", "Quality Lead"],
    publishAt: "2026-07-16T07:00:00",
    endAt: "2026-07-18T17:00:00",
    requireAck: true,
    channels: ["Dashboard", "Email"],
    attachments: 0,
    readership: { read: 31, total: 45 },
    delivery: { delivered: 44, total: 45 },
    acknowledgements: { acked: 12, total: 18 },
  },
  {
    id: "ann-2",
    title: "Doctor pay cut-off reminder",
    type: "Info",
    message: "Doctor pay submissions for week ending 12 Jul close at 14:00 today.",
    clinics: ["all"],
    roles: ["Finance", "Practice Manager"],
    publishAt: "2026-07-16T07:30:00",
    requireAck: false,
    channels: ["Dashboard", "Email"],
    attachments: 0,
    readership: { read: 22, total: 30 },
    delivery: { delivered: 30, total: 30 },
    acknowledgements: { acked: 0, total: 0 },
  },
  {
    id: "ann-3",
    title: "Opening checklist late escalation — Cannon Hill",
    type: "Urgent",
    message: "Cannon Hill opening checklist was not completed by 08:00. Manager follow-up required.",
    clinics: ["loc_cannonhill"],
    roles: ["Practice Manager", "Owner / Director"],
    publishAt: "2026-07-16T08:05:00",
    requireAck: true,
    channels: ["Dashboard", "Email"],
    attachments: 0,
    relatedActionId: "ACT-2026-001291",
    readership: { read: 8, total: 12 },
    delivery: { delivered: 12, total: 12 },
    acknowledgements: { acked: 2, total: 4 },
  },
];

export const AI_FINDINGS: AiFinding[] = [
  {
    id: "ai-1",
    label: "Action Required",
    text: "Beachmere utilities outage remains unacknowledged at Owner level and is blocking all clinic operations.",
    relatedActionId: "ACT-2026-001284",
  },
  {
    id: "ai-2",
    label: "Watch Closely",
    text: "Indooroopilly has three concurrent urgent items across staffing, incidents and systems degradation.",
    relatedActionId: "ACT-2026-001288",
  },
  {
    id: "ai-3",
    label: "Positive Result",
    text: "Woolloongabba and Forest Lake are both above 90% health with no overdue work today.",
  },
  {
    id: "ai-4",
    label: "Recommendation",
    text: "Reassign an experienced PM buddy to Cannon Hill until opening checklist compliance recovers for three consecutive days.",
    relatedActionId: "ACT-2026-001291",
  },
  {
    id: "ai-5",
    label: "Action Required",
    text: "Material doctor pay variance at Indooroopilly exceeds the 5% alert threshold versus forecast.",
    relatedActionId: "ACT-2026-001295",
  },
];

export const COMMAND_ACTIONS: CommandAction[] = [
  {
    id: "ACT-2026-001284",
    reference: "ACT-2026-001284",
    linkedReferences: ["ACT-2026-001284-01"],
    priority: "Emergency",
    title: "Beachmere utilities outage — temporary clinic closure",
    locationId: "loc_beachmere",
    category: "Digital & Security",
    sourceModule: "Emergency Centre",
    owner: "Facilities Lead",
    due: "2026-07-16T09:00:00",
    overdueAge: "2h 18m",
    delayReason: "Awaiting Energex ETA",
    stage: "Escalated",
    reminders: "Emergency — daily",
    escalation: "Owner/Director",
    latestUpdate: "Power still down; temporary signage and call diversion active.",
    attachments: 3,
    summary: "Critical utilities fault forced temporary closure. Patient redirection in place.",
    details:
      "Loss of mains power and network at Beachmere at 05:48. UPS exhausted. Reception phones diverted to Bald Hills. Owner acknowledgement and restoration decision required.",
    comments: [
      {
        id: "c1",
        author: "Laura Dias",
        at: "2026-07-16T06:20:00",
        body: "Clinic secured. Staff stood down pending update.",
      },
    ],
    timeline: [
      { id: "t1", at: "2026-07-16T05:48:00", actor: "System", event: "Outage detected" },
      { id: "t2", at: "2026-07-16T06:15:00", actor: "Laura Dias", event: "Emergency announcement published" },
      { id: "t3", at: "2026-07-16T07:40:00", actor: "System", event: "Escalated to Owner/Director" },
    ],
    relatedActions: ["ACT-2026-001284-01"],
    requiresPassword: true,
  },
  {
    id: "ACT-2026-001284-01",
    reference: "ACT-2026-001284-01",
    linkedReferences: ["ACT-2026-001284"],
    priority: "Urgent",
    title: "Patient redirection plan — Beachmere → Bald Hills / Lawnton",
    locationId: "loc_beachmere",
    category: "Clinic Operations",
    sourceModule: "Emergency Centre",
    owner: "Neil Udukala",
    due: "2026-07-16T10:00:00",
    stage: "In Progress",
    reminders: "Urgent — every two days",
    escalation: "Direct Manager",
    latestUpdate: "Bald Hills accepting overflow; Lawnton on standby.",
    attachments: 1,
    summary: "Linked operational action for patient and staff redirection.",
    details: "Confirm capacity, messaging and clinical handover for redirected patients.",
    comments: [],
    timeline: [
      { id: "t1", at: "2026-07-16T06:30:00", actor: "System", event: "Linked action created from ACT-2026-001284" },
    ],
    relatedActions: ["ACT-2026-001284"],
  },
  {
    id: "ACT-2026-001288",
    reference: "ACT-2026-001288",
    linkedReferences: [],
    priority: "Urgent",
    title: "Unfilled nurse shift + cold-chain risk — Indooroopilly",
    locationId: "loc_indooroopilly",
    category: "Staffing",
    sourceModule: "Roster",
    owner: "James Okonkwo",
    due: "2026-07-16T08:30:00",
    overdueAge: "4h 12m",
    delayReason: "Agency decline",
    stage: "Overdue",
    reminders: "Urgent — every two days",
    escalation: "Area Manager",
    latestUpdate: "Locum nurse declined; internal cover options listed.",
    attachments: 0,
    summary: "Morning nursing gap with cold-chain monitoring exposure.",
    details: "One RN shift unfilled. Cold-chain AM reading owner reassignment required.",
    comments: [],
    timeline: [
      { id: "t1", at: "2026-07-16T05:00:00", actor: "System", event: "Unfilled shift detected" },
    ],
    relatedActions: [],
  },
  {
    id: "ACT-2026-001291",
    reference: "ACT-2026-001291",
    linkedReferences: [],
    priority: "Attention Required",
    title: "Opening checklist late — Cannon Hill",
    locationId: "loc_cannonhill",
    category: "Tasks & Checklists",
    sourceModule: "Front Desk",
    owner: "Sarah Chen",
    due: "2026-07-16T08:00:00",
    overdueAge: "1h 05m",
    stage: "Assigned",
    reminders: "Attention Required — weekly",
    escalation: "Direct Manager",
    latestUpdate: "Checklist started at 08:42; rooms 2 and 3 still pending.",
    attachments: 0,
    summary: "Opening checklist missed 08:00 SLA for second time this week.",
    details: "Repeated late opening checklist creates Attention Required action per pattern rules.",
    comments: [],
    timeline: [
      { id: "t1", at: "2026-07-16T08:05:00", actor: "System", event: "Late opening checklist detected" },
    ],
    relatedActions: [],
  },
  {
    id: "ACT-2026-001292",
    reference: "ACT-2026-001292",
    linkedReferences: [],
    priority: "Urgent",
    title: "AHPRA registration expired — Dr H. Patel",
    locationId: "loc_chapelhill",
    category: "Compliance",
    sourceModule: "Doctors",
    owner: "HR Admin",
    due: "2026-07-12T17:00:00",
    overdueAge: "3d 21h",
    stage: "Awaiting Approval",
    reminders: "Urgent — every two days",
    escalation: "Owner/Director",
    latestUpdate: "Temporary continued use request submitted with controls.",
    attachments: 2,
    summary: "Serious expired credential. Temporary continued use requires Owner decision.",
    details:
      "AHPRA registration expired 12 Jul. Do not auto-block. Management may record temporary continued use with reason and controls.",
    comments: [
      {
        id: "c1",
        author: "Helen Park",
        at: "2026-07-15T16:10:00",
        body: "Requesting temporary continued use pending renewal confirmation. Supervised sessions only.",
      },
    ],
    timeline: [
      { id: "t1", at: "2026-07-12T17:05:00", actor: "System", event: "Expired item created Urgent action" },
    ],
    relatedActions: [],
    requiresPassword: true,
  },
  {
    id: "ACT-2026-001295",
    reference: "ACT-2026-001295",
    linkedReferences: [],
    priority: "Attention Required",
    title: "Doctor pay variance vs forecast — Indooroopilly",
    locationId: "loc_indooroopilly",
    category: "Finance & Pay",
    sourceModule: "Doctor Pay",
    owner: "Finance Lead",
    due: "2026-07-16T14:00:00",
    stage: "In Progress",
    reminders: "Attention Required — weekly",
    escalation: "Direct Manager",
    latestUpdate: "Variance $4,820 (8.4%) under investigation.",
    attachments: 1,
    summary: "Material unusual financial change alert.",
    details: "Expected $57,400; actual $52,580. Dollar and percentage differences shown on Finance panel.",
    comments: [],
    timeline: [
      { id: "t1", at: "2026-07-16T07:15:00", actor: "System", event: "Variance alert raised" },
    ],
    relatedActions: [],
    requiresPassword: true,
  },
  {
    id: "ACT-2026-001296",
    reference: "ACT-2026-001296",
    linkedReferences: [],
    priority: "Urgent",
    title: "Serious complaint — RCA overdue",
    locationId: "loc_cannonhill",
    category: "Incidents",
    sourceModule: "Incidents",
    owner: "Quality Lead",
    due: "2026-07-15T17:00:00",
    overdueAge: "19h",
    stage: "Waiting for Information",
    reminders: "Urgent — every two days",
    escalation: "Area Manager",
    latestUpdate: "Investigator awaiting clinician statement.",
    attachments: 4,
    summary: "Serious complaint at investigation stage requiring executive visibility.",
    details: "Patient complaint regarding wait times and communication. RCA draft incomplete.",
    comments: [],
    timeline: [
      { id: "t1", at: "2026-07-10T11:00:00", actor: "Reception", event: "Complaint logged" },
    ],
    relatedActions: [],
  },
  {
    id: "ACT-2026-001297",
    reference: "ACT-2026-001297",
    linkedReferences: [],
    priority: "Routine",
    title: "Vaccine fridge service booking — Bald Hills",
    locationId: "loc_baldhills",
    category: "Assets & Facilities",
    sourceModule: "Equipment",
    owner: "Facilities",
    due: "2026-07-18T12:00:00",
    stage: "Assigned",
    reminders: "Routine — weekly",
    escalation: "Responsible User",
    latestUpdate: "Supplier quote accepted; booking pending.",
    attachments: 1,
    summary: "Scheduled servicing within SLA.",
    details: "Preventive maintenance for vaccine fridge #BH-FR-02.",
    comments: [],
    timeline: [],
    relatedActions: [],
  },
  {
    id: "ACT-2026-001298",
    reference: "ACT-2026-001298",
    linkedReferences: [],
    priority: "Attention Required",
    title: "Low stock — sterile gloves (size M)",
    locationId: "loc_baldhills",
    category: "Assets & Facilities",
    sourceModule: "Stock",
    owner: "Clinic Manager",
    due: "2026-07-17T10:00:00",
    stage: "Submitted",
    reminders: "Attention Required — weekly",
    escalation: "Direct Manager",
    latestUpdate: "Reorder raised; ETA 2 business days.",
    attachments: 0,
    summary: "Stock below minimum with operational impact on procedures.",
    details: "Current qty 18 boxes vs min 40. Urgent if falls below 10.",
    comments: [],
    timeline: [],
    relatedActions: [],
  },
  {
    id: "ACT-2026-001299",
    reference: "ACT-2026-001299",
    linkedReferences: [],
    priority: "Routine",
    title: "Policy approval — Infection control v4.2",
    locationId: "all",
    category: "Compliance",
    sourceModule: "Policies",
    owner: "Owner / Director",
    due: "2026-07-17T16:00:00",
    stage: "Awaiting Approval",
    reminders: "Routine — weekly",
    escalation: "Owner/Director",
    latestUpdate: "Quality Lead submitted for Owner approval.",
    attachments: 2,
    summary: "Organisation policy awaiting executive approval.",
    details: "Final executive approval retained even if delegated for review.",
    comments: [],
    timeline: [],
    relatedActions: [],
    requiresPassword: true,
  },
  {
    id: "ACT-2026-001300",
    reference: "ACT-2026-001300",
    linkedReferences: [],
    priority: "Completed Today",
    title: "Forest Lake opening checklist complete",
    locationId: "loc_forestlake",
    category: "Tasks & Checklists",
    sourceModule: "Front Desk",
    owner: "Amelia Scott",
    due: "2026-07-16T08:00:00",
    stage: "Completed",
    reminders: "—",
    escalation: "—",
    latestUpdate: "Completed 07:48 — all rooms ready.",
    attachments: 0,
    summary: "Completed opening duties.",
    details: "Remains visible until end of day, then clears from active dashboard.",
    completedAt: "2026-07-16T07:48:00",
    comments: [],
    timeline: [
      { id: "t1", at: "2026-07-16T07:48:00", actor: "Amelia Scott", event: "Marked Complete" },
    ],
    relatedActions: [],
  },
  {
    id: "ACT-2026-001301",
    reference: "ACT-2026-001301",
    linkedReferences: [],
    priority: "Completed Today",
    title: "Supplier invoice approved — Eight Mile Plains",
    locationId: "loc_eightmile",
    category: "Finance & Pay",
    sourceModule: "Finance",
    owner: "Finance Lead",
    due: "2026-07-16T11:00:00",
    stage: "Closed",
    reminders: "—",
    escalation: "—",
    latestUpdate: "Closed after Owner acceptance.",
    attachments: 1,
    summary: "Financial approval completed and formally closed.",
    details: "Completed means work finished; Closed means formally accepted.",
    completedAt: "2026-07-16T09:20:00",
    comments: [],
    timeline: [],
    relatedActions: [],
  },
];

export const POSITIVE_MESSAGES: PositiveMessage[] = [
  { id: "p1", message: "No urgent issues at Woolloongabba and Forest Lake", kind: "status" },
  { id: "p2", message: "No staffing gaps at Chapel Hill", kind: "status" },
  { id: "p3", message: "Compliance on track organisation-wide except Chapel Hill AHPRA item", kind: "status" },
  { id: "p4", message: "Systems healthy across 7 of 9 clinics", kind: "status" },
  { id: "p5", message: "Zero medication fridge temperature breaches this week", kind: "achievement", period: "Weekly" },
  { id: "p6", message: "BBPIP claim acceptance above target for June", kind: "achievement", period: "Monthly" },
];

export const EXECUTIVE_ITEMS: ExecutiveItem[] = [
  {
    id: "ex-1",
    type: "Mandatory announcement",
    title: "Acknowledge Beachmere emergency closure",
    decisionBy: "2026-07-16 10:00",
    locationId: "loc_beachmere",
    actionId: "ACT-2026-001284",
    canDelegate: false,
    priority: "Emergency",
    reason: "Owner acknowledgement required for emergency closure",
    requestedBy: "System",
    responsible: "Neil",
    attachments: 1,
    finalApprovalRequired: true,
  },
  {
    id: "ex-2",
    type: "Compliance sign-off",
    title: "Temporary continued use — Dr H. Patel AHPRA",
    decisionBy: "2026-07-16 12:00",
    locationId: "loc_chapelhill",
    actionId: "ACT-2026-001292",
    canDelegate: true,
    priority: "Urgent",
    reason: "Serious expired registration with temporary use request",
    requestedBy: "Quality Lead",
    responsible: "Neil",
    attachments: 2,
    delegationStatus: "Available",
    finalApprovalRequired: true,
  },
  {
    id: "ex-3",
    type: "Financial approval",
    title: "Approve doctor pay variance investigation outcome",
    decisionBy: "2026-07-16 14:00",
    locationId: "loc_indooroopilly",
    actionId: "ACT-2026-001295",
    canDelegate: true,
    priority: "Urgent",
    reason: "Material doctor pay variance vs forecast",
    requestedBy: "Finance Lead",
    responsible: "Neil",
    attachments: 1,
    finalApprovalRequired: true,
  },
  {
    id: "ex-4",
    type: "Incident review",
    title: "Serious complaint RCA decision — Cannon Hill",
    decisionBy: "2026-07-16 16:00",
    locationId: "loc_cannonhill",
    actionId: "ACT-2026-001296",
    canDelegate: true,
    priority: "Urgent",
    reason: "Executive decision required on RCA outcome",
    requestedBy: "Practice Manager",
    responsible: "Neil",
    attachments: 3,
    finalApprovalRequired: true,
  },
  {
    id: "ex-5",
    type: "Policy approval",
    title: "Infection control policy v4.2",
    decisionBy: "2026-07-17 16:00",
    locationId: "all",
    actionId: "ACT-2026-001299",
    canDelegate: true,
    priority: "Routine",
    reason: "Organisation policy awaiting Owner approval",
    requestedBy: "Quality Lead",
    responsible: "Neil",
    attachments: 1,
    finalApprovalRequired: true,
  },
  {
    id: "ex-6",
    type: "Staffing decision",
    title: "Approve agency cover recommendation — Indooroopilly RN",
    decisionBy: "2026-07-16 09:30",
    locationId: "loc_indooroopilly",
    actionId: "ACT-2026-001288",
    canDelegate: true,
    priority: "Urgent",
    reason: "Unfilled RN shift with agency recommendation only",
    requestedBy: "Area Manager",
    responsible: "Neil",
    attachments: 0,
    finalApprovalRequired: true,
  },
  {
    id: "ex-7",
    type: "Delegated work",
    title: "Final approval on delegated supplier contract review",
    decisionBy: "2026-07-17 11:00",
    locationId: "loc_woolloongabba",
    canDelegate: false,
    priority: "Attention Required",
    reason: "Delegated review complete — final Owner approval retained",
    requestedBy: "Operations Manager",
    responsible: "Neil",
    attachments: 2,
    delegationStatus: "Returned for final approval",
    finalApprovalRequired: true,
  },
];

export const STAFFING: StaffingSnapshot[] = [
  {
    locationId: "loc_baldhills",
    rostered: 14,
    present: 12,
    absent: 1,
    late: 1,
    unfilled: 1,
    overtimeRisk: 2,
    onLeave: 1,
    agencyLocum: 0,
    doctorCoverage: 4,
    gapsByRole: [
      { role: "Nurse", gaps: 1 },
      { role: "Reception", gaps: 0 },
    ],
    nextSevenDayRisks: ["Saturday AM nurse gap", "Monday PM doctor leave"],
    estimatedOvertimeCost: 680,
    coverRecommendations: [
      { role: "Nurse", person: "M. Silva (Lawnton)", reason: "Same credential set · 18 min travel · available AM" },
    ],
  },
  {
    locationId: "loc_indooroopilly",
    rostered: 16,
    present: 11,
    absent: 2,
    late: 1,
    unfilled: 2,
    overtimeRisk: 3,
    onLeave: 2,
    agencyLocum: 1,
    doctorCoverage: 3,
    gapsByRole: [
      { role: "Nurse", gaps: 1 },
      { role: "Reception", gaps: 1 },
    ],
    nextSevenDayRisks: ["Two consecutive RN gaps", "Doctor session uncovered Thu PM"],
    estimatedOvertimeCost: 1240,
    coverRecommendations: [
      { role: "Nurse", person: "Agency — CareFlex", reason: "Only available same-day cover with cold-chain competency" },
      { role: "Reception", person: "A. Perera (Chapel Hill)", reason: "Cross-trained · volunteered for OT" },
    ],
  },
  {
    locationId: "loc_cannonhill",
    rostered: 12,
    present: 11,
    absent: 0,
    late: 1,
    unfilled: 0,
    overtimeRisk: 1,
    onLeave: 0,
    agencyLocum: 0,
    doctorCoverage: 3,
    gapsByRole: [{ role: "Nurse", gaps: 0 }],
    nextSevenDayRisks: ["Friday closing shift short"],
    estimatedOvertimeCost: 220,
    coverRecommendations: [],
  },
];

export const COMPLIANCE_ITEMS: ComplianceItem[] = [
  {
    id: "cmp-1",
    title: "AHPRA registration — Dr H. Patel",
    locationId: "loc_chapelhill",
    group: "Expired",
    subject: "Dr H. Patel",
    due: "2026-07-12",
    serious: true,
    temporaryContinuedUse: {
      reason: "Renewal lodged; confirmation pending",
      controls: "Supervised sessions only; daily credential check",
      recordedBy: "Helen Park",
      at: "2026-07-15T16:10:00",
    },
  },
  {
    id: "cmp-2",
    title: "Fire extinguisher service — Beachmere",
    locationId: "loc_beachmere",
    group: "Due within 7 days",
    subject: "Facilities",
    due: "2026-07-20",
    serious: false,
  },
  {
    id: "cmp-3",
    title: "CPR certification — 3 staff Bald Hills",
    locationId: "loc_baldhills",
    group: "Due within 30 days",
    subject: "Nursing team",
    due: "2026-08-08",
    serious: false,
  },
  {
    id: "cmp-4",
    title: "Privacy training refresh — organisation",
    locationId: "all",
    group: "Due within 60 days",
    subject: "All staff",
    due: "2026-09-01",
    serious: false,
  },
];

export const FINANCE: FinanceSnapshot[] = [
  {
    locationId: "all",
    income: 428450.75,
    expenses: 312880.4,
    profitLoss: 115570.35,
    staffPay: 148220.0,
    doctorPay: 97640.5,
    supplierPayments: 41220.8,
    pendingApprovals: 6,
    forecast: 420000,
    actual: 428450.75,
    pendingAmounts: 18440.0,
    varianceDollar: 8450.75,
    variancePercent: 2.01,
    alerts: [
      {
        title: "Indooroopilly doctor pay vs forecast",
        expected: 57400,
        actual: 52580,
        dollarDiff: -4820,
        percentDiff: -8.4,
      },
    ],
  },
  {
    locationId: "loc_baldhills",
    income: 52400.0,
    expenses: 38120.0,
    profitLoss: 14280.0,
    staffPay: 18200,
    doctorPay: 12400,
    supplierPayments: 4100,
    pendingApprovals: 1,
    forecast: 51000,
    actual: 52400,
    pendingAmounts: 2200,
    varianceDollar: 1400,
    variancePercent: 2.75,
    alerts: [],
  },
  {
    locationId: "loc_indooroopilly",
    income: 61200.0,
    expenses: 49880.0,
    profitLoss: 11320.0,
    staffPay: 21400,
    doctorPay: 52580,
    supplierPayments: 5200,
    pendingApprovals: 2,
    forecast: 64000,
    actual: 61200,
    pendingAmounts: 4800,
    varianceDollar: -2800,
    variancePercent: -4.38,
    alerts: [
      {
        title: "Doctor pay unusual change",
        expected: 57400,
        actual: 52580,
        dollarDiff: -4820,
        percentDiff: -8.4,
      },
    ],
  },
];

export const INCIDENTS: IncidentRecord[] = [
  {
    id: "inc-1",
    title: "Patient complaint — wait time and communication",
    type: "Complaint",
    locationId: "loc_cannonhill",
    stage: "Investigation / RCA",
    investigator: "Quality Lead",
    due: "2026-07-15",
    rca: "Draft incomplete",
    correctiveActions: "Reception scripting refresh proposed",
    latestUpdate: "Awaiting clinician statement",
    serious: true,
    actionId: "ACT-2026-001296",
  },
  {
    id: "inc-2",
    title: "Near miss — vaccine fridge door left ajar",
    type: "Incident",
    locationId: "loc_eightmile",
    stage: "Corrective actions",
    investigator: "Nursing Lead",
    due: "2026-07-18",
    rca: "Complete",
    correctiveActions: "Door alarm installed; checklist updated",
    latestUpdate: "Awaiting Owner note on lesson dissemination",
    executiveDecision: "Pending",
    serious: false,
    actionId: undefined,
  },
];

export const TASK_DELIVERY: TaskDeliverySummary[] = [
  {
    locationId: "all",
    completionPercent: 86,
    openTasks: 27,
    checklistsDue: 9,
    meetingActions: 5,
    openingMissed: 2,
    closingMissed: 1,
    roomReadinessGaps: 3,
    managerFollowUps: 4,
    repeatedMissPattern: "Cannon Hill opening checklist late 2× this week → Attention Required",
  },
  {
    locationId: "loc_cannonhill",
    completionPercent: 71,
    openTasks: 6,
    checklistsDue: 2,
    meetingActions: 1,
    openingMissed: 2,
    closingMissed: 0,
    roomReadinessGaps: 1,
    managerFollowUps: 2,
    repeatedMissPattern: "Opening checklist late pattern",
  },
  {
    locationId: "loc_woolloongabba",
    completionPercent: 97,
    openTasks: 1,
    checklistsDue: 0,
    meetingActions: 0,
    openingMissed: 0,
    closingMissed: 0,
    roomReadinessGaps: 0,
    managerFollowUps: 0,
  },
];

export const ASSETS: AssetFacilitiesSnapshot[] = [
  {
    locationId: "all",
    assetValue: 1854000,
    unavailableEquipment: 3,
    lowStock: 7,
    serviceCalibrationDue: 5,
    openWorkOrders: 8,
    supplierIssues: 2,
    expectedCosts: 12640,
    impactNotes: ["Beachmere network/UPS unavailable", "Bald Hills sterile gloves below minimum"],
  },
];

export const DIGITAL: DigitalSecuritySnapshot[] = [
  {
    locationId: "all",
    availabilityPercent: 97.2,
    activeOutages: 1,
    businessImpact: "Beachmere closed; phones diverted",
    restorationEstimate: "Today 14:00–16:00 (utility ETA)",
    websites: "Up",
    internet: "Degraded",
    phones: "Degraded",
    practiceSystems: "Degraded",
    backupStatus: "Current",
  },
  {
    locationId: "loc_beachmere",
    availabilityPercent: 0,
    activeOutages: 1,
    businessImpact: "Full clinic outage",
    restorationEstimate: "Today 14:00–16:00",
    websites: "Up",
    internet: "Down",
    phones: "Down",
    practiceSystems: "Down",
    backupStatus: "Current",
  },
];

export const TRENDS: TrendCard[] = [
  {
    id: "tr-1",
    title: "Organisation health",
    area: "Overall",
    result: "82%",
    change: "-2 pts WoW",
    direction: "down",
    size: "Large",
    series: [86, 85, 84, 83, 84, 82],
    explanation: "Decline driven by Beachmere emergency and Indooroopilly concurrent urgents.",
    recommendations: ["Resolve Beachmere utilities", "Stabilise Indooroopilly staffing cover"],
    clinicComparison: [
      { clinic: "Woolloongabba", value: 94 },
      { clinic: "Forest Lake", value: 90 },
      { clinic: "Bald Hills", value: 88 },
      { clinic: "Indooroopilly", value: 72 },
      { clinic: "Beachmere", value: 61 },
    ],
    tableRows: [
      { label: "This week", value: "82%" },
      { label: "Last week", value: "84%" },
      { label: "Change", value: "-2 pts" },
    ],
  },
  {
    id: "tr-2",
    title: "Staffing fill rate",
    area: "Staffing",
    result: "91%",
    change: "-3 pts",
    direction: "down",
    size: "Medium",
    series: [95, 94, 93, 94, 92, 91],
    explanation: "Fill rate dipped due to Indooroopilly and Bald Hills unfilled shifts.",
    recommendations: ["Approve recommended cover without cross-clinic forced moves"],
    clinicComparison: [
      { clinic: "Chapel Hill", value: 100 },
      { clinic: "Indooroopilly", value: 78 },
    ],
    tableRows: [
      { label: "Fill rate", value: "91%" },
      { label: "Unfilled today", value: "3" },
    ],
  },
  {
    id: "tr-3",
    title: "Compliance %",
    area: "Compliance",
    result: "94%",
    change: "+1 pt",
    direction: "up",
    size: "Small",
    series: [92, 92, 93, 93, 94, 94],
    explanation: "Organisation compliance improved; one serious expiry remains.",
    recommendations: ["Close AHPRA temporary use decision today"],
    clinicComparison: [],
    tableRows: [{ label: "Compliance", value: "94%" }],
  },
  {
    id: "tr-4",
    title: "Net profit (MTD)",
    area: "Finance & Pay",
    result: "$115,570",
    change: "+2.0% vs forecast",
    direction: "up",
    size: "Medium",
    series: [98, 102, 105, 108, 112, 116],
    explanation: "Organisation ahead of forecast despite Indooroopilly doctor pay variance.",
    recommendations: ["Review Indooroopilly variance before pay cut-off"],
    clinicComparison: [
      { clinic: "Bald Hills", value: 14280 },
      { clinic: "Indooroopilly", value: 11320 },
    ],
    tableRows: [
      { label: "Income", value: "$428,450.75" },
      { label: "Expenses", value: "$312,880.40" },
      { label: "P/L", value: "$115,570.35" },
    ],
  },
];

export const RECENT_ACTIVITY: ActivityItem[] = [
  {
    id: "acty-1",
    title: "Emergency announcement published — Beachmere",
    at: "2026-07-16T06:15:00",
    importance: "Critical",
    summary: "Temporary closure and patient diversion activated.",
    locationId: "loc_beachmere",
    pinned: true,
    read: false,
    actionId: "ACT-2026-001284",
  },
  {
    id: "acty-2",
    title: "Escalated to Owner/Director — utilities outage",
    at: "2026-07-16T07:40:00",
    importance: "Critical",
    summary: "Escalation path reached Owner/Director.",
    locationId: "loc_beachmere",
    pinned: true,
    actionId: "ACT-2026-001284",
  },
  {
    id: "acty-3",
    title: "Opening checklist late — Cannon Hill",
    at: "2026-07-16T08:05:00",
    importance: "High",
    summary: "Second late occurrence this week.",
    locationId: "loc_cannonhill",
    actionId: "ACT-2026-001291",
  },
  {
    id: "acty-4",
    title: "Doctor pay variance alert",
    at: "2026-07-16T07:15:00",
    importance: "High",
    summary: "8.4% below forecast at Indooroopilly.",
    locationId: "loc_indooroopilly",
    actionId: "ACT-2026-001295",
  },
  {
    id: "acty-5",
    title: "Forest Lake opening checklist completed",
    at: "2026-07-16T07:48:00",
    importance: "Medium",
    summary: "Positive completion before SLA.",
    locationId: "loc_forestlake",
    actionId: "ACT-2026-001300",
  },
  {
    id: "acty-6",
    title: "Temporary continued use recorded — Dr Patel",
    at: "2026-07-15T16:10:00",
    importance: "High",
    summary: "Awaiting Owner password-confirmed decision.",
    locationId: "loc_chapelhill",
    actionId: "ACT-2026-001292",
  },
  {
    id: "acty-7",
    title: "Supplier invoice closed — Eight Mile Plains",
    at: "2026-07-16T09:20:00",
    importance: "Medium",
    summary: "Formally accepted by finance workflow.",
    locationId: "loc_eightmile",
    actionId: "ACT-2026-001301",
  },
  {
    id: "acty-8",
    title: "Agency cover recommendation generated",
    at: "2026-07-16T08:20:00",
    importance: "High",
    summary: "Dashboard recommends cover; does not move staff.",
    locationId: "loc_indooroopilly",
    actionId: "ACT-2026-001288",
  },
  {
    id: "acty-9",
    title: "Compliance pack reminder delivered",
    at: "2026-07-16T07:00:00",
    importance: "Medium",
    summary: "44 of 45 recipients delivered.",
    locationId: "all",
  },
  {
    id: "acty-10",
    title: "Policy v4.2 submitted for Owner approval",
    at: "2026-07-15T17:30:00",
    importance: "Medium",
    summary: "Infection control policy awaiting decision.",
    locationId: "all",
    actionId: "ACT-2026-001299",
  },
];

export const DEFAULT_SECTIONS: DashboardSectionLayout[] = [
  { id: "priority", label: "Priority Summary", visible: true, size: "Medium", collapsed: false, order: 0 },
  { id: "categories", label: "Category Filters", visible: true, size: "Small", collapsed: false, order: 1 },
  { id: "ai", label: "AI Executive Briefing", visible: true, size: "Medium", collapsed: false, order: 2 },
  { id: "actions", label: "Active Action List", visible: true, size: "Large", collapsed: false, order: 3 },
  { id: "positive", label: "Positive Health Summary", visible: true, size: "Small", collapsed: false, order: 4 },
  { id: "completed", label: "Completed Today", visible: true, size: "Medium", collapsed: false, order: 5 },
  { id: "executive", label: "My Executive Actions", visible: true, size: "Medium", collapsed: false, order: 6 },
  { id: "clinics", label: "Clinic Operations & Comparison", visible: true, size: "Large", collapsed: false, order: 7 },
  { id: "staffing", label: "Staffing & Roster", visible: true, size: "Medium", collapsed: false, order: 8 },
  { id: "compliance", label: "Compliance & Expiries", visible: true, size: "Medium", collapsed: false, order: 9 },
  { id: "finance", label: "Finance & Pay", visible: true, size: "Large", collapsed: false, order: 10 },
  { id: "incidents", label: "Incidents, Complaints & Risk", visible: true, size: "Medium", collapsed: false, order: 11 },
  { id: "tasks", label: "Tasks & Operational Delivery", visible: true, size: "Medium", collapsed: false, order: 12 },
  { id: "assets", label: "Assets, Suppliers & Facilities", visible: true, size: "Medium", collapsed: false, order: 13 },
  { id: "digital", label: "Websites, Systems & Security", visible: true, size: "Medium", collapsed: false, order: 14 },
  { id: "trends", label: "Performance Trends", visible: true, size: "Large", collapsed: false, order: 15 },
  { id: "activity", label: "Recent Activity", visible: true, size: "Medium", collapsed: false, order: 16 },
];

export const CATEGORY_LIST: ActionCategory[] = [
  "Clinic Operations",
  "Staffing",
  "Compliance",
  "Finance & Pay",
  "Incidents",
  "Tasks & Checklists",
  "Assets & Facilities",
  "Digital & Security",
];

export const PRIORITY_ORDER = [
  "Emergency",
  "Urgent",
  "Attention Required",
  "Routine",
  "Overdue",
  "Completed Today",
] as const;
