import type {
  ClinicAssignment,
  OrgClinic,
  OrgDepartment,
  OrgNode,
  OrgUser,
  PermissionException,
  ReportingRelationship,
  RoleDefinition,
} from "./types";

const PERM = (opts: Partial<Record<"view" | "create" | "edit" | "delete" | "approve" | "export" | "assign" | "manageSettings" | "viewSensitive", boolean>>) => ({
  view: false,
  create: false,
  edit: false,
  delete: false,
  approve: false,
  export: false,
  assign: false,
  manageSettings: false,
  viewSensitive: false,
  ...opts,
});

export const CURRENT_ACTOR = {
  id: "usr_sarah",
  name: "Sarah Mitchell",
  role: "Senior Administrator" as const,
};

export const ROLE_DEFS: RoleDefinition[] = [
  {
    id: "role_receptionist",
    name: "Receptionist",
    description: "Front desk operations and patient flow support.",
    level: "Standard Access",
    permissions: PERM({ view: true, create: true, edit: true }),
    sensitive: false,
  },
  {
    id: "role_sr_receptionist",
    name: "Senior Receptionist",
    description: "Leads reception team and daily desk coverage.",
    level: "Standard Access",
    permissions: PERM({ view: true, create: true, edit: true, assign: true }),
    sensitive: false,
  },
  {
    id: "role_nurse",
    name: "Nurse",
    description: "Clinical nursing duties and treatment room access.",
    level: "Standard Access",
    permissions: PERM({ view: true, create: true, edit: true, viewSensitive: true }),
    sensitive: true,
  },
  {
    id: "role_doctor",
    name: "Doctor",
    description: "Consulting practitioners with clinical permissions.",
    level: "Standard Access",
    permissions: PERM({ view: true, create: true, edit: true, viewSensitive: true, export: true }),
    sensitive: true,
  },
  {
    id: "role_pm",
    name: "Practice Manager",
    description: "Clinic operations, roster oversight and approvals.",
    level: "Manager Access",
    permissions: PERM({
      view: true,
      create: true,
      edit: true,
      approve: true,
      export: true,
      assign: true,
      viewSensitive: true,
    }),
    sensitive: true,
  },
  {
    id: "role_rm",
    name: "Regional Manager",
    description: "Multi-clinic oversight across a region.",
    level: "Manager Access",
    permissions: PERM({
      view: true,
      create: true,
      edit: true,
      approve: true,
      export: true,
      assign: true,
      manageSettings: true,
      viewSensitive: true,
    }),
    sensitive: true,
  },
  {
    id: "role_finance",
    name: "Finance Officer",
    description: "Pay and commercial reporting access.",
    level: "Standard Access",
    permissions: PERM({ view: true, edit: true, export: true, viewSensitive: true }),
    sensitive: true,
  },
  {
    id: "role_admin",
    name: "Senior Administrator",
    description: "Organisation structure, users and permissions.",
    level: "Full Administration",
    permissions: PERM({
      view: true,
      create: true,
      edit: true,
      delete: true,
      approve: true,
      export: true,
      assign: true,
      manageSettings: true,
      viewSensitive: true,
    }),
    sensitive: true,
  },
  {
    id: "role_director",
    name: "Director",
    description: "Executive authority across the organisation.",
    level: "Full Administration",
    permissions: PERM({
      view: true,
      create: true,
      edit: true,
      delete: true,
      approve: true,
      export: true,
      assign: true,
      manageSettings: true,
      viewSensitive: true,
    }),
    sensitive: true,
  },
  {
    id: "role_contractor",
    name: "External Contractor",
    description: "Limited time-bound access for specialists.",
    level: "View Only",
    permissions: PERM({ view: true }),
    sensitive: false,
  },
  {
    id: "role_auditor",
    name: "Read-Only Auditor",
    description: "Audit and evidence review without change rights.",
    level: "View Only",
    permissions: PERM({ view: true, export: true, viewSensitive: true }),
    sensitive: true,
  },
];

const defaultHours = (
  service: OrgClinic["serviceHours"][number]["service"],
  weekdays: string,
  weekend = "Closed"
): OrgClinic["serviceHours"][number] => ({
  service,
  monday: weekdays,
  tuesday: weekdays,
  wednesday: weekdays,
  thursday: weekdays,
  friday: weekdays,
  saturday: weekend,
  sunday: "Closed",
});

function readiness(done: boolean[]): OrgClinic["readiness"] {
  const labels = [
    "Practice manager assigned",
    "Opening hours confirmed",
    "Primary rooms listed",
    "Emergency contacts set",
    "Public holiday region set",
    "Activation approved by Director / Senior Administrator",
  ];
  return labels.map((label, i) => ({
    id: `ready_${i}`,
    label,
    done: !!done[i],
    required: true,
  }));
}

export const SEED_NODES: OrgNode[] = [
  { id: "org_parent", name: "Healthcare Doctors Group Pty Ltd", level: "Parent Company", parentId: null },
  { id: "bg_metro", name: "Metro Queensland", level: "Business Group", parentId: "org_parent" },
  { id: "bg_coastal", name: "Coastal & Regional", level: "Business Group", parentId: "org_parent" },
  { id: "reg_brisbane_south", name: "Brisbane South", level: "Region", parentId: "bg_metro" },
  { id: "reg_brisbane_west", name: "Brisbane West", level: "Region", parentId: "bg_metro" },
  { id: "reg_north", name: "Northside Corridor", level: "Region", parentId: "bg_coastal" },
  { id: "reg_moreton", name: "Moreton Bay", level: "Region", parentId: "bg_coastal" },
];

export const SEED_CLINICS: OrgClinic[] = [
  {
    id: "loc_woolloongabba",
    name: "Woolloongabba Medical Centre",
    tradingName: "Gabba Medical Centre",
    shortName: "Woolloongabba",
    address: "468 Vulture Street, Woolloongabba QLD 4102",
    suburb: "Woolloongabba",
    state: "QLD",
    postcode: "4102",
    phone: "07 3217 3344",
    email: "reception@gabbamedicalcentre.com.au",
    status: "Active",
    practiceManager: "Priya Nair",
    practiceManagerId: "usr_priya",
    regionId: "reg_brisbane_south",
    businessGroupId: "bg_metro",
    openingHoursSummary: "Monâ€“Fri 8:00â€“17:30 Â· Sat 8:00â€“12:00",
    serviceHours: [
      defaultHours("General Practice", "08:00â€“17:30", "08:00â€“12:00"),
      defaultHours("After-Hours", "17:30â€“20:00", "Closed"),
      defaultHours("Pathology", "08:00â€“15:00", "Closed"),
      defaultHours("Treatment Room", "08:00â€“17:00", "08:00â€“12:00"),
      defaultHours("Telehealth", "08:00â€“17:30", "09:00â€“12:00"),
      defaultHours("Additional Services", "By appointment", "Closed"),
    ],
    holidays: [
      { id: "hol1", date: "2026-12-25", name: "Christmas Day", type: "Public Holiday", reason: "Public holiday" },
    ],
    activeUsers: 28,
    warnings: [],
    lat: -27.4855,
    lng: 153.028,
    isDraft: false,
    readiness: readiness([true, true, true, true, true, true]),
    createdAt: "2024-01-12",
  },
  {
    id: "loc_baldhills",
    name: "Bald Hills Doctors",
    tradingName: "Bald Hills Doctors",
    shortName: "Bald Hills",
    address: "1425 Gympie Road, Bald Hills QLD 4036",
    suburb: "Bald Hills",
    state: "QLD",
    postcode: "4036",
    phone: "07 3261 9117",
    email: "reception@baldhillsdoctors.com.au",
    status: "Active",
    practiceManager: "James Okafor",
    practiceManagerId: "usr_james",
    regionId: "reg_north",
    businessGroupId: "bg_coastal",
    openingHoursSummary: "Monâ€“Fri 8:00â€“17:00",
    serviceHours: [
      defaultHours("General Practice", "08:00â€“17:00"),
      defaultHours("After-Hours", "Closed"),
      defaultHours("Pathology", "08:00â€“14:00"),
      defaultHours("Treatment Room", "08:00â€“16:30"),
      defaultHours("Telehealth", "09:00â€“16:00"),
      defaultHours("Additional Services", "By appointment"),
    ],
    holidays: [],
    activeUsers: 18,
    warnings: ["2 temporary access assignments expiring within 3 days"],
    lat: -27.3208,
    lng: 153.0089,
    isDraft: false,
    readiness: readiness([true, true, true, true, true, true]),
    createdAt: "2024-03-01",
  },
  {
    id: "loc_cannonhill",
    name: "Cannon Hill Family Doctors",
    tradingName: "Cannon Hill Family Doctors",
    shortName: "Cannon Hill",
    address: "17/1177 Wynnum Rd, Cannon Hill QLD 4170",
    suburb: "Cannon Hill",
    state: "QLD",
    postcode: "4170",
    phone: "07 3399 2200",
    email: "reception@cannonhillfd.com.au",
    status: "Active",
    practiceManager: "Elena Brooks",
    practiceManagerId: "usr_elena",
    regionId: "reg_brisbane_south",
    businessGroupId: "bg_metro",
    openingHoursSummary: "Monâ€“Fri 8:00â€“18:00 Â· Sat 8:00â€“13:00",
    serviceHours: [
      defaultHours("General Practice", "08:00â€“18:00", "08:00â€“13:00"),
      defaultHours("After-Hours", "18:00â€“20:00", "Closed"),
      defaultHours("Pathology", "08:00â€“15:30"),
      defaultHours("Treatment Room", "08:00â€“17:30", "08:00â€“12:00"),
      defaultHours("Telehealth", "08:00â€“18:00", "09:00â€“12:00"),
      defaultHours("Additional Services", "By appointment"),
    ],
    holidays: [],
    activeUsers: 22,
    warnings: ["Access reviews overdue for 3 users"],
    lat: -27.472,
    lng: 153.099,
    isDraft: false,
    readiness: readiness([true, true, true, true, true, true]),
    createdAt: "2023-11-20",
  },
  {
    id: "loc_eightmile",
    name: "Eight Mile Plains Family Doctors",
    tradingName: "Eight Mile Plains Family Doctors",
    shortName: "Eight Mile Plains",
    address: "Shop 7, Warrigal Square, 261 Warrigal Rd, Eight Mile Plains QLD 4113",
    suburb: "Eight Mile Plains",
    state: "QLD",
    postcode: "4113",
    phone: "07 3341 8800",
    email: "reception@empfd.com.au",
    status: "Temporarily Closed",
    practiceManager: "Daniel Chen",
    practiceManagerId: "usr_daniel",
    regionId: "reg_brisbane_south",
    businessGroupId: "bg_metro",
    openingHoursSummary: "Temporarily closed â€” diverting to Cannon Hill",
    serviceHours: [
      defaultHours("General Practice", "Closed", "Closed"),
      defaultHours("After-Hours", "Closed", "Closed"),
      defaultHours("Pathology", "Closed", "Closed"),
      defaultHours("Treatment Room", "Closed", "Closed"),
      defaultHours("Telehealth", "Remote redirect", "Closed"),
      defaultHours("Additional Services", "Closed", "Closed"),
    ],
    holidays: [
      {
        id: "tc1",
        date: "2026-07-01",
        name: "Roof remedial works",
        type: "Temporary Closure",
        reason: "Building safety works",
      },
    ],
    activeUsers: 6,
    warnings: ["Clinic temporarily closed â€” temporary cover assignments active"],
    lat: -27.579,
    lng: 153.094,
    isDraft: false,
    readiness: readiness([true, true, true, true, true, true]),
    statusReason: "Roof structural remedial works â€” temporary diversion",
    statusEffectiveDate: "2026-07-01",
    createdAt: "2023-06-15",
  },
  {
    id: "loc_chapelhill",
    name: "Chapel Hill Family Doctors",
    tradingName: "Chapel Hill Family Doctors",
    shortName: "Chapel Hill",
    address: "2 Kirkdale Road, Chapel Hill QLD 4069",
    suburb: "Chapel Hill",
    state: "QLD",
    postcode: "4069",
    phone: "07 3172 9910",
    email: "reception@chapelhilldoctors.com.au",
    status: "Merging",
    practiceManager: "Amelia Grant",
    practiceManagerId: "usr_amelia",
    regionId: "reg_brisbane_west",
    businessGroupId: "bg_metro",
    openingHoursSummary: "Monâ€“Fri 8:00â€“17:00 (merger in progress)",
    serviceHours: [
      defaultHours("General Practice", "08:00â€“17:00"),
      defaultHours("After-Hours", "Closed"),
      defaultHours("Pathology", "08:00â€“14:00"),
      defaultHours("Treatment Room", "08:00â€“16:30"),
      defaultHours("Telehealth", "09:00â€“16:00"),
      defaultHours("Additional Services", "By appointment"),
    ],
    holidays: [],
    activeUsers: 14,
    warnings: ["Clinic merger in progress with Indooroopilly"],
    lat: -27.502,
    lng: 152.95,
    isDraft: false,
    readiness: readiness([true, true, true, true, true, true]),
    statusReason: "Consolidate west Brisbane services",
    statusEffectiveDate: "2026-08-15",
    mergerPartnerId: "loc_indooroopilly",
    mergerMethod: "Create combined clinic",
    createdAt: "2022-09-01",
  },
  {
    id: "loc_indooroopilly",
    name: "Healthcare Doctors Indooroopilly",
    tradingName: "Healthcare Doctors Indooroopilly",
    shortName: "Indooroopilly",
    address: "11 Musgrave Rd, Indooroopilly QLD 4068",
    suburb: "Indooroopilly",
    state: "QLD",
    postcode: "4068",
    phone: "07 3519 4666",
    email: "info.indooroopilly@healthcaredoctors.com.au",
    status: "Merging",
    practiceManager: "Amelia Grant",
    practiceManagerId: "usr_amelia",
    regionId: "reg_brisbane_west",
    businessGroupId: "bg_metro",
    openingHoursSummary: "Monâ€“Fri 8:00â€“18:00 (merger in progress)",
    serviceHours: [
      defaultHours("General Practice", "08:00â€“18:00"),
      defaultHours("After-Hours", "18:00â€“20:00"),
      defaultHours("Pathology", "08:00â€“15:00"),
      defaultHours("Treatment Room", "08:00â€“17:00"),
      defaultHours("Telehealth", "08:00â€“18:00"),
      defaultHours("Additional Services", "By appointment"),
    ],
    holidays: [],
    activeUsers: 24,
    warnings: ["Receiving users from Chapel Hill merger"],
    lat: -27.499,
    lng: 152.973,
    isDraft: false,
    readiness: readiness([true, true, true, true, true, true]),
    statusReason: "Consolidate west Brisbane services",
    statusEffectiveDate: "2026-08-15",
    mergerPartnerId: "loc_chapelhill",
    mergerMethod: "Create combined clinic",
    createdAt: "2021-04-18",
  },
  {
    id: "loc_forestlake",
    name: "Forest Lake Doctors",
    tradingName: "Forest Lake Doctors",
    shortName: "Forest Lake",
    address: "Shop 12, Forest Lake Shopping Centre, Forest Lake QLD 4078",
    suburb: "Forest Lake",
    state: "QLD",
    postcode: "4078",
    phone: "07 3278 8877",
    email: "reception@forestlakedoctors.com.au",
    status: "Under Renovation",
    practiceManager: "Marcus Lee",
    practiceManagerId: "usr_marcus",
    regionId: "reg_brisbane_west",
    businessGroupId: "bg_metro",
    openingHoursSummary: "Under renovation â€” Treatment Room and Annex closed",
    serviceHours: [
      defaultHours("General Practice", "08:00â€“17:30", "08:30â€“12:00"),
      defaultHours("After-Hours", "Closed"),
      defaultHours("Pathology", "08:00â€“14:30"),
      defaultHours("Treatment Room", "Closed"),
      defaultHours("Telehealth", "09:00â€“17:00"),
      defaultHours("Additional Services", "By appointment"),
    ],
    holidays: [],
    activeUsers: 16,
    warnings: ["Clinic under renovation — restricted access to Treatment Room and Annex"],
    lat: -27.624,
    lng: 152.965,
    isDraft: false,
    readiness: readiness([true, true, true, true, true, true]),
    statusReason: "Annex renovation and treatment room upgrade",
    statusEffectiveDate: "2026-07-05",
    createdAt: "2023-02-10",
  },
  {
    id: "loc_lawnton",
    name: "Lawnton Country Market Medical Centre",
    tradingName: "Lawnton Medical Centre",
    shortName: "Lawnton",
    address: "Country Market, Lawnton QLD 4501",
    suburb: "Lawnton",
    state: "QLD",
    postcode: "4501",
    phone: "07 3205 8119",
    email: "reception@lawntonmedicals.com.au",
    status: "Setup in Progress",
    practiceManager: "Not assigned",
    regionId: "reg_moreton",
    businessGroupId: "bg_coastal",
    openingHoursSummary: "Setup in progress",
    serviceHours: [
      defaultHours("General Practice", "TBC"),
      defaultHours("After-Hours", "TBC"),
      defaultHours("Pathology", "TBC"),
      defaultHours("Treatment Room", "TBC"),
      defaultHours("Telehealth", "TBC"),
      defaultHours("Additional Services", "TBC"),
    ],
    holidays: [],
    activeUsers: 2,
    warnings: ["Setup checklist incomplete â€” clinic remains Draft until activation"],
    lat: -27.28,
    lng: 152.985,
    isDraft: true,
    readiness: readiness([false, true, false, false, true, false]),
    createdAt: "2026-06-20",
  },
  {
    id: "loc_beachmere",
    name: "Beachmere Medical Centre",
    tradingName: "Beachmere Medical Centre",
    shortName: "Beachmere",
    address: "12 Moreton Terrace, Beachmere QLD 4510",
    suburb: "Beachmere",
    state: "QLD",
    postcode: "4510",
    phone: "",
    email: "",
    status: "Planned",
    practiceManager: "Not assigned",
    regionId: "reg_moreton",
    businessGroupId: "bg_coastal",
    openingHoursSummary: "Planned â€” not yet opened",
    serviceHours: [
      defaultHours("General Practice", "TBC"),
      defaultHours("After-Hours", "TBC"),
      defaultHours("Pathology", "TBC"),
      defaultHours("Treatment Room", "TBC"),
      defaultHours("Telehealth", "TBC"),
      defaultHours("Additional Services", "TBC"),
    ],
    holidays: [],
    activeUsers: 0,
    warnings: ["Planned clinic â€” complete short form then guided setup"],
    lat: -27.13,
    lng: 153.05,
    isDraft: true,
    readiness: readiness([false, false, false, false, false, false]),
    createdAt: "2026-07-01",
  },
  {
    id: "loc_combined_west",
    name: "Healthcare Doctors West Brisbane",
    tradingName: "Healthcare Doctors West Brisbane",
    shortName: "West Brisbane (new)",
    address: "11 Musgrave Rd, Indooroopilly QLD 4068",
    suburb: "Indooroopilly",
    state: "QLD",
    postcode: "4068",
    phone: "07 3519 4666",
    email: "west@healthcaredoctors.com.au",
    status: "Draft",
    practiceManager: "Amelia Grant",
    practiceManagerId: "usr_amelia",
    regionId: "reg_brisbane_west",
    businessGroupId: "bg_metro",
    openingHoursSummary: "Draft combined clinic (merger outcome)",
    serviceHours: [
      defaultHours("General Practice", "08:00â€“18:00", "08:00â€“12:00"),
      defaultHours("After-Hours", "18:00â€“20:00"),
      defaultHours("Pathology", "08:00â€“15:00"),
      defaultHours("Treatment Room", "08:00â€“17:00"),
      defaultHours("Telehealth", "08:00â€“18:00"),
      defaultHours("Additional Services", "By appointment"),
    ],
    holidays: [],
    activeUsers: 0,
    warnings: ["Draft combined clinic awaiting merger completion checklist"],
    lat: -27.499,
    lng: 152.973,
    isDraft: true,
    readiness: readiness([true, true, false, true, true, false]),
    mergerPartnerId: "loc_chapelhill",
    mergerMethod: "Create combined clinic",
    createdAt: "2026-07-10",
  },
];

export const SEED_RELATIONSHIPS: ReportingRelationship[] = [
  { id: "rel1", clinicId: "loc_woolloongabba", reportsToNodeId: "reg_brisbane_south", isPrimary: true },
  { id: "rel2", clinicId: "loc_cannonhill", reportsToNodeId: "reg_brisbane_south", isPrimary: true },
  { id: "rel3", clinicId: "loc_eightmile", reportsToNodeId: "reg_brisbane_south", isPrimary: true },
  { id: "rel4", clinicId: "loc_chapelhill", reportsToNodeId: "reg_brisbane_west", isPrimary: true },
  { id: "rel5", clinicId: "loc_indooroopilly", reportsToNodeId: "reg_brisbane_west", isPrimary: true },
  { id: "rel6", clinicId: "loc_forestlake", reportsToNodeId: "reg_brisbane_west", isPrimary: true },
  { id: "rel7", clinicId: "loc_baldhills", reportsToNodeId: "reg_north", isPrimary: true },
  { id: "rel8", clinicId: "loc_lawnton", reportsToNodeId: "reg_moreton", isPrimary: true },
  { id: "rel9", clinicId: "loc_beachmere", reportsToNodeId: "reg_moreton", isPrimary: true },
  { id: "rel10", clinicId: "loc_combined_west", reportsToNodeId: "reg_brisbane_west", isPrimary: true },
  { id: "rel11", clinicId: "loc_forestlake", reportsToNodeId: "bg_metro", isPrimary: false },
];

export const SEED_USERS: OrgUser[] = [
  {
    id: "usr_sarah",
    firstName: "Sarah",
    lastName: "Mitchell",
    email: "sarah.mitchell@healthcaredoctors.com.au",
    phone: "0400 111 001",
    status: "Active",
    primaryClinicId: "loc_woolloongabba",
    role: "Senior Administrator",
    secondaryRoles: [],
    jobTitle: "Group Senior Administrator",
    employmentType: "Full-time",
    startDate: "2020-03-01",
    trainingComplete: true,
    verificationComplete: true,
    lastLogin: "2026-07-20T08:12:00",
    failedSignIns: 0,
    emergencyAccessActive: false,
    accessIssues: [],
    createdVia: "Manual entry",
  },
  {
    id: "usr_priya",
    firstName: "Priya",
    lastName: "Nair",
    email: "priya.nair@healthcaredoctors.com.au",
    phone: "0400 111 002",
    status: "Active",
    primaryClinicId: "loc_woolloongabba",
    role: "Practice Manager",
    secondaryRoles: [],
    jobTitle: "Practice Manager",
    employmentType: "Full-time",
    managerId: "usr_sarah",
    managerName: "Sarah Mitchell",
    startDate: "2021-06-15",
    trainingComplete: true,
    verificationComplete: true,
    lastLogin: "2026-07-19T17:40:00",
    failedSignIns: 0,
    emergencyAccessActive: false,
    accessIssues: [],
    createdVia: "Existing staff record",
  },
  {
    id: "usr_james",
    firstName: "James",
    lastName: "Okafor",
    email: "james.okafor@healthcaredoctors.com.au",
    phone: "0400 111 003",
    status: "Active",
    primaryClinicId: "loc_baldhills",
    role: "Practice Manager",
    secondaryRoles: ["Regional Manager"],
    jobTitle: "Practice Manager / Acting Regional",
    employmentType: "Full-time",
    managerId: "usr_sarah",
    managerName: "Sarah Mitchell",
    startDate: "2019-11-01",
    trainingComplete: true,
    verificationComplete: true,
    lastLogin: "2026-07-20T07:55:00",
    failedSignIns: 0,
    emergencyAccessActive: false,
    accessIssues: ["Temporary cover at Eight Mile Plains expiring soon"],
    createdVia: "Manual entry",
  },
  {
    id: "usr_elena",
    firstName: "Elena",
    lastName: "Brooks",
    email: "elena.brooks@healthcaredoctors.com.au",
    phone: "0400 111 004",
    status: "Access Review Required",
    primaryClinicId: "loc_cannonhill",
    role: "Practice Manager",
    secondaryRoles: [],
    jobTitle: "Practice Manager",
    employmentType: "Full-time",
    managerId: "usr_sarah",
    managerName: "Sarah Mitchell",
    startDate: "2022-01-10",
    trainingComplete: true,
    verificationComplete: true,
    lastLogin: "2026-07-18T09:10:00",
    failedSignIns: 0,
    emergencyAccessActive: false,
    accessIssues: ["Overdue access review", "Permission exception nearing review date"],
    createdVia: "Manager request",
  },
  {
    id: "usr_daniel",
    firstName: "Daniel",
    lastName: "Chen",
    email: "daniel.chen@healthcaredoctors.com.au",
    phone: "0400 111 005",
    status: "On Leave",
    primaryClinicId: "loc_eightmile",
    role: "Practice Manager",
    secondaryRoles: [],
    jobTitle: "Practice Manager",
    employmentType: "Full-time",
    managerId: "usr_sarah",
    managerName: "Sarah Mitchell",
    startDate: "2020-08-20",
    trainingComplete: true,
    verificationComplete: true,
    lastLogin: "2026-06-28T16:00:00",
    failedSignIns: 0,
    emergencyAccessActive: false,
    accessIssues: ["Return-from-leave access review pending"],
    createdVia: "Existing staff record",
  },
  {
    id: "usr_amelia",
    firstName: "Amelia",
    lastName: "Grant",
    email: "amelia.grant@healthcaredoctors.com.au",
    phone: "0400 111 006",
    status: "Active",
    primaryClinicId: "loc_indooroopilly",
    role: "Practice Manager",
    secondaryRoles: [],
    jobTitle: "Practice Manager (West Brisbane merger lead)",
    employmentType: "Full-time",
    managerId: "usr_sarah",
    managerName: "Sarah Mitchell",
    startDate: "2018-05-01",
    trainingComplete: true,
    verificationComplete: true,
    lastLogin: "2026-07-20T08:01:00",
    failedSignIns: 0,
    emergencyAccessActive: false,
    accessIssues: ["Primary clinic change review required after merger"],
    createdVia: "Manual entry",
  },
  {
    id: "usr_marcus",
    firstName: "Marcus",
    lastName: "Lee",
    email: "marcus.lee@healthcaredoctors.com.au",
    phone: "0400 111 007",
    status: "Active",
    primaryClinicId: "loc_forestlake",
    role: "Practice Manager",
    secondaryRoles: [],
    jobTitle: "Practice Manager",
    employmentType: "Full-time",
    managerId: "usr_sarah",
    managerName: "Sarah Mitchell",
    startDate: "2023-03-12",
    trainingComplete: true,
    verificationComplete: true,
    lastLogin: "2026-07-19T18:22:00",
    failedSignIns: 0,
    emergencyAccessActive: false,
    accessIssues: [],
    createdVia: "Bulk import",
  },
  {
    id: "usr_tom",
    firstName: "Tom",
    lastName: "Nguyen",
    email: "tom.nguyen@healthcaredoctors.com.au",
    phone: "0400 111 008",
    status: "Locked",
    primaryClinicId: "loc_woolloongabba",
    role: "Receptionist",
    secondaryRoles: [],
    jobTitle: "Receptionist",
    employmentType: "Part-time",
    managerId: "usr_priya",
    managerName: "Priya Nair",
    startDate: "2024-09-01",
    trainingComplete: true,
    verificationComplete: true,
    lastLogin: "2026-07-17T11:05:00",
    failedSignIns: 6,
    emergencyAccessActive: false,
    accessIssues: ["Account locked after repeated failed sign-ins"],
    createdVia: "Manager request",
  },
  {
    id: "usr_lucy",
    firstName: "Lucy",
    lastName: "Wright",
    email: "lucy.wright@healthcaredoctors.com.au",
    phone: "0400 111 009",
    status: "Active",
    primaryClinicId: "loc_cannonhill",
    role: "Nurse",
    secondaryRoles: [],
    jobTitle: "Practice Nurse",
    employmentType: "Full-time",
    managerId: "usr_elena",
    managerName: "Elena Brooks",
    startDate: "2022-07-01",
    trainingComplete: true,
    verificationComplete: true,
    lastLogin: "2026-07-20T07:30:00",
    failedSignIns: 0,
    emergencyAccessActive: true,
    accessIssues: ["Emergency access active"],
    createdVia: "Existing staff record",
  },
  {
    id: "usr_raj",
    firstName: "Raj",
    lastName: "Patel",
    email: "raj.patel@healthcaredoctors.com.au",
    phone: "0400 111 010",
    status: "Active",
    primaryClinicId: "loc_indooroopilly",
    role: "Doctor",
    secondaryRoles: [],
    jobTitle: "General Practitioner",
    employmentType: "Contractor",
    managerId: "usr_amelia",
    managerName: "Amelia Grant",
    startDate: "2021-02-01",
    trainingComplete: true,
    verificationComplete: true,
    lastLogin: "2026-07-19T19:10:00",
    failedSignIns: 0,
    emergencyAccessActive: false,
    accessIssues: [],
    createdVia: "Existing staff record",
  },
  {
    id: "usr_nina",
    firstName: "Nina",
    lastName: "Costa",
    email: "nina.costa@contractor.example.com",
    phone: "0400 111 011",
    status: "Invited",
    primaryClinicId: "loc_baldhills",
    role: "External Contractor",
    secondaryRoles: [],
    jobTitle: "IT Support Contractor",
    employmentType: "Contractor",
    managerId: "usr_james",
    managerName: "James Okafor",
    startDate: "2026-07-18",
    trainingComplete: false,
    verificationComplete: false,
    failedSignIns: 0,
    emergencyAccessActive: false,
    accessIssues: ["Invitation pending acceptance"],
    createdVia: "Manual entry",
  },
  {
    id: "usr_owen",
    firstName: "Owen",
    lastName: "Fraser",
    email: "owen.fraser@healthcaredoctors.com.au",
    phone: "0400 111 012",
    status: "Pending Approval",
    primaryClinicId: "loc_forestlake",
    role: "Finance Officer",
    secondaryRoles: [],
    jobTitle: "Finance Officer",
    employmentType: "Full-time",
    managerId: "usr_sarah",
    managerName: "Sarah Mitchell",
    startDate: "2026-07-15",
    trainingComplete: false,
    verificationComplete: false,
    failedSignIns: 0,
    emergencyAccessActive: false,
    accessIssues: ["Awaiting dual approval for sensitive finance access"],
    createdVia: "Manager request",
  },
  {
    id: "usr_kate",
    firstName: "Kate",
    lastName: "Holloway",
    email: "kate.holloway@healthcaredoctors.com.au",
    phone: "0400 111 013",
    status: "Temporarily Suspended",
    primaryClinicId: "loc_cannonhill",
    role: "Senior Receptionist",
    secondaryRoles: [],
    jobTitle: "Senior Receptionist",
    employmentType: "Full-time",
    managerId: "usr_elena",
    managerName: "Elena Brooks",
    startDate: "2020-01-15",
    trainingComplete: true,
    verificationComplete: true,
    lastLogin: "2026-07-10T12:00:00",
    failedSignIns: 1,
    emergencyAccessActive: false,
    accessIssues: ["Temporarily suspended pending investigation"],
    createdVia: "Manual entry",
  },
  {
    id: "usr_helen",
    firstName: "Helen",
    lastName: "Zhou",
    email: "helen.zhou@healthcaredoctors.com.au",
    phone: "0400 111 014",
    status: "Archived",
    primaryClinicId: "loc_woolloongabba",
    role: "Receptionist",
    secondaryRoles: [],
    jobTitle: "Receptionist",
    employmentType: "Casual",
    managerId: "usr_priya",
    managerName: "Priya Nair",
    startDate: "2023-04-01",
    trainingComplete: true,
    verificationComplete: true,
    lastLogin: "2026-05-30T09:00:00",
    failedSignIns: 0,
    emergencyAccessActive: false,
    accessIssues: ["Employment ended — access archived for compliance history"],
    createdVia: "Existing staff record",
  },
  {
    id: "usr_david",
    firstName: "David",
    lastName: "King",
    email: "david.king@healthcaredoctors.com.au",
    phone: "0400 111 015",
    status: "Active",
    primaryClinicId: "loc_woolloongabba",
    role: "Director",
    secondaryRoles: [],
    jobTitle: "Managing Director",
    employmentType: "Full-time",
    startDate: "2015-01-01",
    trainingComplete: true,
    verificationComplete: true,
    lastLogin: "2026-07-19T21:00:00",
    failedSignIns: 0,
    emergencyAccessActive: false,
    accessIssues: [],
    createdVia: "Manual entry",
  },
  {
    id: "usr_audit",
    firstName: "Grace",
    lastName: "Mbeki",
    email: "grace.mbeki@auditor.example.com",
    phone: "0400 111 016",
    status: "Active",
    primaryClinicId: "loc_woolloongabba",
    role: "Read-Only Auditor",
    secondaryRoles: [],
    jobTitle: "External Auditor",
    employmentType: "Contractor",
    managerId: "usr_david",
    managerName: "David King",
    startDate: "2026-06-01",
    trainingComplete: true,
    verificationComplete: true,
    lastLogin: "2026-07-18T14:00:00",
    failedSignIns: 0,
    emergencyAccessActive: false,
    accessIssues: [],
    createdVia: "Manual entry",
  },
];

export const SEED_ASSIGNMENTS: ClinicAssignment[] = [
  { id: "as1", userId: "usr_sarah", clinicId: "loc_woolloongabba", type: "Primary Clinic", startDate: "2020-03-01" },
  { id: "as2", userId: "usr_sarah", clinicId: "loc_cannonhill", type: "Organisation-Wide Access", startDate: "2020-03-01" },
  { id: "as3", userId: "usr_priya", clinicId: "loc_woolloongabba", type: "Primary Clinic", startDate: "2021-06-15" },
  { id: "as4", userId: "usr_james", clinicId: "loc_baldhills", type: "Primary Clinic", startDate: "2019-11-01" },
  {
    id: "as5",
    userId: "usr_james",
    clinicId: "loc_eightmile",
    type: "Temporary Cover",
    startDate: "2026-07-01",
    endDate: "2026-07-23",
    warningDaysSent: [7],
    reason: "Cover while Eight Mile Plains temporarily closed",
  },
  { id: "as6", userId: "usr_elena", clinicId: "loc_cannonhill", type: "Primary Clinic", startDate: "2022-01-10" },
  { id: "as7", userId: "usr_elena", clinicId: "loc_woolloongabba", type: "Permanent Additional Clinic", startDate: "2025-11-01" },
  { id: "as8", userId: "usr_daniel", clinicId: "loc_eightmile", type: "Primary Clinic", startDate: "2020-08-20" },
  { id: "as9", userId: "usr_amelia", clinicId: "loc_indooroopilly", type: "Primary Clinic", startDate: "2018-05-01" },
  { id: "as10", userId: "usr_amelia", clinicId: "loc_chapelhill", type: "Permanent Additional Clinic", startDate: "2026-06-01" },
  { id: "as11", userId: "usr_marcus", clinicId: "loc_forestlake", type: "Primary Clinic", startDate: "2023-03-12" },
  { id: "as12", userId: "usr_tom", clinicId: "loc_woolloongabba", type: "Primary Clinic", startDate: "2024-09-01" },
  { id: "as13", userId: "usr_lucy", clinicId: "loc_cannonhill", type: "Primary Clinic", startDate: "2022-07-01" },
  {
    id: "as14",
    userId: "usr_lucy",
    clinicId: "loc_eightmile",
    type: "Emergency Access",
    startDate: "2026-07-19",
    endDate: "2026-07-21T18:00:00",
    reason: "Emergency nursing cover",
  },
  { id: "as15", userId: "usr_raj", clinicId: "loc_indooroopilly", type: "Primary Clinic", startDate: "2021-02-01" },
  { id: "as16", userId: "usr_raj", clinicId: "loc_chapelhill", type: "Regional Support", startDate: "2025-01-01" },
  { id: "as17", userId: "usr_david", clinicId: "loc_woolloongabba", type: "Organisation-Wide Access", startDate: "2015-01-01" },
  { id: "as18", userId: "usr_audit", clinicId: "loc_woolloongabba", type: "Read-Only Access", startDate: "2026-06-01" },
  { id: "as19", userId: "usr_nina", clinicId: "loc_baldhills", type: "Primary Clinic", startDate: "2026-07-18" },
  { id: "as20", userId: "usr_owen", clinicId: "loc_forestlake", type: "Primary Clinic", startDate: "2026-07-15" },
  {
    id: "as21",
    userId: "usr_james",
    clinicId: "loc_lawnton",
    type: "Temporary Cover",
    startDate: "2026-07-10",
    endDate: "2026-07-22",
    warningDaysSent: [7, 3],
    reason: "Setup support for Lawnton",
  },
];

const AREA_NAMES = [
  "Reception",
  "Waiting Room",
  "Nursing Station",
  "Treatment Room 1",
  "Treatment Room 2",
  "Consulting Room 1",
  "Consulting Room 2",
  "Consulting Room 3",
  "Pathology Collection",
  "Vaccination Room",
  "Admin Office",
  "Staff Room",
  "Medicine Store",
  "Telehealth Booth",
  "Procedure Room",
];

function buildDepartments(): OrgDepartment[] {
  const activeClinicIds = [
    "loc_woolloongabba",
    "loc_baldhills",
    "loc_cannonhill",
    "loc_indooroopilly",
    "loc_forestlake",
  ];
  const deps: OrgDepartment[] = [];
  let n = 1;
  for (const clinicId of activeClinicIds) {
    AREA_NAMES.forEach((name, i) => {
      const restricted = name === "Medicine Store" || name === "Procedure Room";
      deps.push({
        id: `dep_${n++}`,
        clinicId,
        name,
        building: i < 8 ? "Main Building" : "Annex",
        floor: i < 5 ? "Ground" : i < 10 ? "Level 1" : "Level 2",
        zone: i < 3 ? "Front of House" : i < 9 ? "Clinical" : "Support",
        primaryPersonId: clinicId === "loc_woolloongabba" ? "usr_priya" : "usr_james",
        primaryPersonName: clinicId === "loc_woolloongabba" ? "Priya Nair" : "Clinic Lead",
        backupPersonId: "usr_sarah",
        backupPersonName: "Sarah Mitchell",
        status: restricted
          ? "Restricted Access"
          : name === "Treatment Room 2" && clinicId === "loc_cannonhill"
            ? "Under Maintenance"
            : name === "Telehealth Booth" && clinicId === "loc_baldhills"
              ? "Temporarily Unavailable"
              : "Active",
        restricted,
        archived: false,
        notes: restricted ? "Requires Manager Access to enter" : undefined,
      });
    });
  }
  deps.push({
    id: `dep_${n}`,
    clinicId: "loc_eightmile",
    name: "Reception",
    building: "Main Building",
    floor: "Ground",
    zone: "Front of House",
    primaryPersonId: "usr_daniel",
    primaryPersonName: "Daniel Chen",
    backupPersonId: "usr_james",
    backupPersonName: "James Okafor",
    status: "Temporarily Unavailable",
    restricted: false,
    archived: false,
    notes: "Clinic temporarily closed",
  });
  return deps;
}

export const SEED_DEPARTMENTS = buildDepartments();

export const SEED_EXCEPTIONS: PermissionException[] = [
  {
    id: "ex1",
    userId: "usr_elena",
    permissionKey: "export.sensitive.payroll",
    level: "Manager Access",
    reason: "Month-end payroll reconciliation while Finance Officer is vacant",
    approvingManagerId: "usr_david",
    approvingManagerName: "David King",
    startDate: "2026-07-01",
    reviewDate: "2026-07-21",
    expiryDate: "2026-07-31",
    auditId: "aud_ex1",
  },
];
