import type {
  AccessRequest,
  AccessReview,
  AuditEntry,
  EmergencyAccess,
  OrgNotification,
  OrgReportDef,
  OrgSettings,
  OrgState,
  SavedView,
  SecurityAlert,
} from "./types";
import {
  CURRENT_ACTOR,
  ROLE_DEFS,
  SEED_ASSIGNMENTS,
  SEED_CLINICS,
  SEED_DEPARTMENTS,
  SEED_EXCEPTIONS,
  SEED_NODES,
  SEED_RELATIONSHIPS,
  SEED_USERS,
} from "./mock-data";

const aid = "approverId" as const;
const aname = "approverName" as const;

function approver(
  id: string,
  name: string,
  decidedAt?: string,
  decision?: "Approved" | "Rejected"
) {
  return {
    [aid]: id,
    [aname]: name,
    ...(decidedAt ? { decidedAt } : {}),
    ...(decision ? { decision } : {}),
  } as AccessRequest["approvals"][number];
}

const SEED_REQUESTS: AccessRequest[] = [
  {
    id: "req1",
    title: "Finance Officer onboarding — Forest Lake",
    requesterId: "usr_marcus",
    requesterName: "Marcus Lee",
    subjectUserId: "usr_owen",
    subjectUserName: "Owen Fraser",
    clinicId: "loc_forestlake",
    priority: "Complex Administration",
    status: "In Review",
    submittedAt: "2026-07-15T09:00:00",
    dueAt: "2026-07-22T17:00:00",
    riskSummary: "Includes sensitive finance export and multi-clinic read access.",
    riskLevel: "High",
    requiresTwoApprovers: true,
    approvals: [approver("usr_sarah", "Sarah Mitchell"), approver("usr_david", "David King")],
    items: [
      { id: "ri1", label: "Finance Officer role", risk: "High", status: "Pending" },
      { id: "ri2", label: "Payroll export", risk: "Critical", status: "Pending" },
      { id: "ri3", label: "Forest Lake primary clinic", risk: "Low", status: "Approved" },
      { id: "ri4", label: "Read-only Woolloongabba finance pack", risk: "Medium", status: "Pending" },
    ],
    decisionHistory: [],
  },
  {
    id: "req2",
    title: "Emergency nursing cover — Eight Mile Plains",
    requesterId: "usr_james",
    requesterName: "James Okafor",
    subjectUserId: "usr_lucy",
    subjectUserName: "Lucy Wright",
    clinicId: "loc_eightmile",
    priority: "Emergency",
    status: "Approved",
    submittedAt: "2026-07-19T07:15:00",
    dueAt: "2026-07-19T07:30:00",
    riskSummary: "Emergency Access with treatment room permissions.",
    riskLevel: "Critical",
    requiresTwoApprovers: true,
    approvals: [
      approver("usr_sarah", "Sarah Mitchell", "2026-07-19T07:20:00", "Approved"),
      approver("usr_david", "David King", "2026-07-19T07:22:00", "Approved"),
    ],
    items: [
      { id: "ri5", label: "Emergency Access assignment", risk: "Critical", status: "Approved" },
      { id: "ri6", label: "Treatment Room restricted area", risk: "High", status: "Approved" },
    ],
    decisionHistory: ["Approved by Sarah Mitchell", "Second approval by David King"],
  },
  {
    id: "req3",
    title: "Contractor portal access — Bald Hills",
    requesterId: "usr_james",
    requesterName: "James Okafor",
    subjectUserId: "usr_nina",
    subjectUserName: "Nina Costa",
    clinicId: "loc_baldhills",
    priority: "Standard",
    status: "Rejected",
    submittedAt: "2026-07-12T10:00:00",
    dueAt: "2026-07-14T17:00:00",
    riskSummary: "External contractor requesting admin settings — reduced to view only.",
    riskLevel: "Medium",
    requiresTwoApprovers: false,
    approvals: [approver("usr_sarah", "Sarah Mitchell", "2026-07-13T11:00:00", "Rejected")],
    items: [
      {
        id: "ri7",
        label: "Manage Settings permission",
        risk: "High",
        status: "Rejected",
        decisionNote: "Not required for IT contractor",
      },
      { id: "ri8", label: "View Only clinic access", risk: "Low", status: "Approved" },
    ],
    decisionHistory: ["Manage Settings rejected — View Only retained for re-invite"],
  },
  {
    id: "req4",
    title: "Permanent additional clinic — Elena Brooks",
    requesterId: "usr_elena",
    requesterName: "Elena Brooks",
    subjectUserId: "usr_elena",
    subjectUserName: "Elena Brooks",
    clinicId: "loc_woolloongabba",
    priority: "Urgent",
    status: "In Review",
    submittedAt: "2026-07-20T08:00:00",
    dueAt: "2026-07-20T12:00:00",
    riskSummary: "Self-requested permission increase — self-approval blocked.",
    riskLevel: "High",
    requiresTwoApprovers: true,
    approvals: [approver("usr_sarah", "Sarah Mitchell"), approver("usr_david", "David King")],
    items: [{ id: "ri9", label: "Assign role changes at Woolloongabba", risk: "High", status: "Pending" }],
    decisionHistory: [],
  },
];

const SEED_REVIEWS: AccessReview[] = [
  {
    id: "rev1",
    userId: "usr_elena",
    userName: "Elena Brooks",
    clinicId: "loc_cannonhill",
    trigger: "Scheduled",
    status: "Overdue",
    dueDate: "2026-07-10",
    riskLevel: "High",
    ownerName: "Sarah Mitchell",
  },
  {
    id: "rev2",
    userId: "usr_daniel",
    userName: "Daniel Chen",
    clinicId: "loc_eightmile",
    trigger: "Return from leave",
    status: "Open",
    dueDate: "2026-07-25",
    riskLevel: "Medium",
    ownerName: "Sarah Mitchell",
  },
  {
    id: "rev3",
    userId: "usr_amelia",
    userName: "Amelia Grant",
    clinicId: "loc_indooroopilly",
    trigger: "Primary Clinic change",
    status: "In Progress",
    dueDate: "2026-07-28",
    riskLevel: "High",
    ownerName: "David King",
  },
  {
    id: "rev4",
    userId: "usr_lucy",
    userName: "Lucy Wright",
    clinicId: "loc_eightmile",
    trigger: "Emergency access expiry",
    status: "Open",
    dueDate: "2026-07-22",
    riskLevel: "Critical",
    ownerName: "Sarah Mitchell",
  },
  {
    id: "rev5",
    userId: "usr_james",
    userName: "James Okafor",
    clinicId: "loc_baldhills",
    trigger: "Sensitive access",
    status: "Completed",
    dueDate: "2026-06-30",
    riskLevel: "Medium",
    ownerName: "Sarah Mitchell",
    decision: "Confirm",
    notes: "Multi-clinic coverage confirmed for temporary closures",
    completedAt: "2026-06-28",
  },
];

const SEED_EMERGENCY: EmergencyAccess[] = [
  {
    id: "em1",
    userId: "usr_lucy",
    userName: "Lucy Wright",
    clinicId: "loc_eightmile",
    reason: "Urgent treatment room cover while clinic temporarily closed",
    permissions: "Nurse Standard Access + Restricted Treatment Room",
    [aid]: "usr_sarah",
    [aname]: "Sarah Mitchell",
    expiresAt: "2026-07-21T18:00:00",
    verified: true,
    active: true,
    reviewCreated: false,
  } as EmergencyAccess,
];

const SEED_ALERTS: SecurityAlert[] = [
  {
    id: "al1",
    title: "Account locked — Tom Nguyen",
    category: "Locked account",
    risk: "High",
    clinicId: "loc_woolloongabba",
    userId: "usr_tom",
    createdAt: "2026-07-17T11:06:00",
    resolved: false,
  },
  {
    id: "al2",
    title: "Six failed sign-ins — Tom Nguyen",
    category: "Failed sign-in",
    risk: "Medium",
    clinicId: "loc_woolloongabba",
    userId: "usr_tom",
    createdAt: "2026-07-17T11:05:00",
    resolved: false,
  },
  {
    id: "al3",
    title: "Emergency access active — Lucy Wright",
    category: "Emergency access",
    risk: "Critical",
    clinicId: "loc_eightmile",
    userId: "usr_lucy",
    createdAt: "2026:07-19T07:22:00",
    resolved: false,
  },
  {
    id: "al4",
    title: "Overdue access review — Elena Brooks",
    category: "Overdue review",
    risk: "High",
    clinicId: "loc_cannonhill",
    userId: "usr_elena",
    createdAt: "2026-07-11T09:00:00",
    resolved: false,
  },
  {
    id: "al5",
    title: "Permission increase requested — Elena Brooks",
    category: "Permission increase",
    risk: "High",
    clinicId: "loc_woolloongabba",
    userId: "usr_elena",
    createdAt: "2026-07-20T08:00:00",
    resolved: false,
  },
  {
    id: "al6",
    title: "Unusual export volume — Finance pack",
    category: "Unusual export",
    risk: "Medium",
    clinicId: "loc_forestlake",
    userId: "usr_marcus",
    createdAt: "2026-07-18T16:40:00",
    resolved: false,
  },
  {
    id: "al7",
    title: "Unassigned-clinic access attempt — Beachmere",
    category: "Unassigned clinic access",
    risk: "High",
    clinicId: "loc_beachmere",
    userId: "usr_nina",
    createdAt: "2026-07-19T10:12:00",
    resolved: false,
  },
  {
    id: "al8",
    title: "High-risk administrator accounts under watch",
    category: "High-risk administrator",
    risk: "Critical",
    userId: "usr_sarah",
    createdAt: "2026-07-01T00:00:00",
    resolved: false,
  },
];

const SEED_AUDIT: AuditEntry[] = [
  {
    id: "aud1",
    at: "2026-07-19T07:22:00",
    actorId: "usr_david",
    actorName: "David King",
    entityType: "Approval",
    entityId: "req2",
    entityLabel: "Emergency nursing cover",
    field: "status",
    previousValue: "In Review",
    newValue: "Approved",
    reason: "Second approval for emergency nursing cover",
    approval: "Dual approval complete",
    device: "Desktop · Chrome",
    locationLabel: "Woolloongabba office",
    relatedRequestId: "req2",
    correctionNotes: [],
  },
  {
    id: "aud2",
    at: "2026-07-19T07:20:00",
    actorId: "usr_sarah",
    actorName: "Sarah Mitchell",
    entityType: "Assignment",
    entityId: "as14",
    entityLabel: "Lucy Wright → Eight Mile Plains",
    field: "type",
    previousValue: "—",
    newValue: "Emergency Access",
    reason: "Urgent treatment room cover",
    approval: "Approved by Sarah Mitchell",
    device: "Desktop · Edge",
    locationLabel: "Woolloongabba",
    relatedRequestId: "req2",
    correctionNotes: [],
  },
  {
    id: "aud3",
    at: "2026-07-17T11:06:00",
    actorId: "system",
    actorName: "System",
    entityType: "Security",
    entityId: "usr_tom",
    entityLabel: "Tom Nguyen",
    field: "status",
    previousValue: "Active",
    newValue: "Locked",
    reason: "Automatic lock after 5 failed sign-ins",
    device: "Unknown",
    locationLabel: "IP 203.45.12.88",
    correctionNotes: [],
  },
  {
    id: "aud4",
    at: "2026-07-01T09:00:00",
    actorId: "usr_sarah",
    actorName: "Sarah Mitchell",
    entityType: "Clinic",
    entityId: "loc_eightmile",
    entityLabel: "Eight Mile Plains Family Doctors",
    field: "status",
    previousValue: "Active",
    newValue: "Temporarily Closed",
    reason: "Roof structural remedial works — temporary diversion",
    approval: "Director approved",
    device: "Desktop · Chrome",
    locationLabel: "Head office",
    correctionNotes: [
      {
        at: "2026-07-02T10:00:00",
        by: "Sarah Mitchell",
        note: "Clarified diversion clinic is Cannon Hill; original status reason retained.",
      },
    ],
  },
  {
    id: "aud5",
    at: "2026-07-10T14:00:00",
    actorId: "usr_amelia",
    actorName: "Amelia Grant",
    entityType: "Clinic",
    entityId: "loc_chapelhill",
    entityLabel: "Chapel Hill Family Doctors",
    field: "status",
    previousValue: "Active",
    newValue: "Merging",
    reason: "Consolidate west Brisbane services",
    approval: "Director approved",
    device: "Desktop · Chrome",
    locationLabel: "Indooroopilly",
    correctionNotes: [],
  },
  {
    id: "aud6",
    at: "2026-07-15T09:05:00",
    actorId: "usr_marcus",
    actorName: "Marcus Lee",
    entityType: "User",
    entityId: "usr_owen",
    entityLabel: "Owen Fraser",
    field: "status",
    previousValue: "—",
    newValue: "Pending Approval",
    reason: "Manager request for Finance Officer",
    relatedRequestId: "req1",
    device: "Desktop · Chrome",
    locationLabel: "Forest Lake",
    correctionNotes: [],
  },
  {
    id: "aud_ex1",
    at: "2026-07-01T08:30:00",
    actorId: "usr_david",
    actorName: "David King",
    entityType: "Permission",
    entityId: "ex1",
    entityLabel: "Elena Brooks payroll export exception",
    field: "exception",
    previousValue: "Standard Access",
    newValue: "Manager Access (temporary)",
    reason: "Month-end payroll reconciliation while Finance Officer is vacant",
    approval: "David King",
    device: "Desktop · Chrome",
    locationLabel: "Head office",
    correctionNotes: [],
  },
];

const SEED_NOTIFICATIONS: OrgNotification[] = [
  {
    id: "nt1",
    title: "Emergency access active",
    body: "Lucy Wright has emergency access at Eight Mile Plains until 21 Jul 6:00 pm.",
    type: "Emergency access",
    channels: ["Platform", "Email", "SMS"],
    mandatory: true,
    createdAt: "2026-07-19T07:22:00",
    read: false,
    resolved: false,
    actionLabel: "Open monitoring",
    actionSection: "security",
  },
  {
    id: "nt2",
    title: "Access request awaiting approval",
    body: "Finance Officer onboarding for Owen Fraser needs two approvers.",
    type: "Access request",
    channels: ["Platform", "Email"],
    mandatory: true,
    createdAt: "2026-07-15T09:00:00",
    read: false,
    resolved: false,
    actionLabel: "Review request",
    actionSection: "access-requests",
    actionFilter: "req1",
  },
  {
    id: "nt3",
    title: "Account locked",
    body: "Tom Nguyen locked after failed sign-ins.",
    type: "Account lock",
    channels: ["Platform", "Email", "SMS"],
    mandatory: true,
    createdAt: "2026-07-17T11:06:00",
    read: true,
    resolved: false,
    actionLabel: "Open user",
    actionSection: "users",
    actionFilter: "usr_tom",
  },
  {
    id: "nt4",
    title: "Temporary access expiring",
    body: "James Okafor temporary cover at Eight Mile Plains expires in 3 days.",
    type: "Temporary expiry",
    channels: ["Platform", "Email"],
    mandatory: true,
    createdAt: "2026-07-20T07:00:00",
    read: false,
    resolved: false,
    actionLabel: "Review assignment",
    actionSection: "users",
    actionFilter: "usr_james",
  },
  {
    id: "nt5",
    title: "Clinic status changed",
    body: "Eight Mile Plains set to Temporarily Closed.",
    type: "Clinic status",
    channels: ["Platform", "Email"],
    mandatory: false,
    createdAt: "2026-07-01T09:00:00",
    read: true,
    resolved: true,
    actionLabel: "Open clinic",
    actionSection: "locations",
    actionFilter: "loc_eightmile",
  },
];

const SEED_REPORTS: OrgReportDef[] = [
  { id: "rp1", name: "Clinic profile register", description: "All clinics with lifecycle status, managers and warnings.", category: "Locations" },
  { id: "rp2", name: "User and permission matrix", description: "Roles, clinics and permission levels by user.", category: "Users" },
  { id: "rp3", name: "Access review report", description: "Open, overdue and completed reviews by risk.", category: "Reviews" },
  { id: "rp4", name: "Inactive user and clinic report", description: "Ended, archived and closed records retaining history.", category: "Compliance" },
  { id: "rp5", name: "Sensitive activity audit", description: "Permission changes, exports and emergency access.", category: "Audit" },
  { id: "rp6", name: "Temporary access expiry forecast", description: "Assignments nearing 7 / 3 / 1 day warnings.", category: "Assignments" },
  { id: "rp7", name: "Security alert summary", description: "Open alerts by risk level and category.", category: "Security" },
];

const SEED_VIEWS: SavedView[] = [
  {
    id: "sv1",
    name: "My overdue reviews",
    section: "access-reviews",
    shared: false,
    filters: { status: "Overdue" },
    createdBy: CURRENT_ACTOR.name,
  },
  {
    id: "sv2",
    name: "Clinics with warnings",
    section: "locations",
    shared: true,
    filters: { status: "warnings" },
    createdBy: CURRENT_ACTOR.name,
  },
];

const SEED_SETTINGS: OrgSettings = {
  defaultReviewFrequencyDays: 90,
  temporaryAccessExpiryWarnings: [7, 3, 1],
  dualApprovalThreshold: "High",
  allowClinicSettingExceptions: true,
  notificationChannels: {
    "Access request": ["Platform", "Email"],
    "Permission change": ["Platform", "Email"],
    "Emergency access": ["Platform", "Email", "SMS"],
    "Account lock": ["Platform", "Email", "SMS"],
    "Critical alert": ["Platform", "Email", "SMS"],
    "Clinic status": ["Platform", "Email"],
    "Access removal": ["Platform", "Email"],
    "Temporary expiry": ["Platform", "Email"],
  },
  mandatoryNotificationTypes: [
    "Emergency access",
    "Account lock",
    "Critical alert",
    "Access removal",
    "Permission change",
  ],
};

export function createInitialOrgState(): OrgState {
  // Fix typo in alert timestamp if present
  const alerts = SEED_ALERTS.map((a) =>
    a.id === "al3" ? { ...a, createdAt: "2026-07-19T07:22:00" } : a
  );

  return {
    currentUserId: CURRENT_ACTOR.id,
    nodes: [
      ...SEED_NODES,
      ...SEED_CLINICS.map((c) => ({
        id: `node_${c.id}`,
        name: c.shortName,
        level: "Clinic" as const,
        parentId: c.regionId,
        clinicId: c.id,
      })),
    ],
    relationships: SEED_RELATIONSHIPS,
    clinics: SEED_CLINICS,
    departments: SEED_DEPARTMENTS,
    users: SEED_USERS,
    roles: ROLE_DEFS,
    assignments: SEED_ASSIGNMENTS,
    exceptions: SEED_EXCEPTIONS,
    requests: SEED_REQUESTS,
    reviews: SEED_REVIEWS,
    emergency: SEED_EMERGENCY,
    alerts,
    audit: SEED_AUDIT,
    notifications: SEED_NOTIFICATIONS,
    reports: SEED_REPORTS,
    savedViews: SEED_VIEWS,
    settings: SEED_SETTINGS,
    demoClockOffsetMs: 0,
  };
}
