import type {
  ActionDraft,
  ActionTemplate,
  AuditEntry,
  DelegationRecord,
  InboxAction,
  InboxNotification,
  SavedView,
} from "./types";
import { DEFAULT_FILTERS } from "./types";

const T0 = "2026-07-20T10:00:00.000Z";

function base(
  partial: Omit<InboxAction, "ownershipHistory" | "linkedFollowUps" | "completionRequirements" | "notificationMethods" | "attachments" | "comments" | "relatedRecords" | "approvalSteps" | "watchers" | "notes" | "escalationLevel" | "unread" | "isDemo" | "sensitivity" | "team"> &
    Partial<InboxAction>
): InboxAction {
  return {
    team: "Clinic Operations",
    sensitivity: "Standard",
    unread: false,
    isDemo: true,
    escalationLevel: 0,
    watchers: [],
    notes: "",
    attachments: [],
    comments: [],
    relatedRecords: [],
    approvalSteps: [],
    ownershipHistory: [],
    linkedFollowUps: [],
    completionRequirements: ["Completion note"],
    notificationMethods: ["Platform"],
    ...partial,
  };
}

/** Demonstration seed — clearly labelled Demonstration Data in the UI */
export const SEED_ACTIONS: InboxAction[] = [
  base({
    id: "m2-inv-1",
    number: "ACT-2026-1042",
    title: "Invoice approval — medical supplies July",
    explanation: "Supplier invoice exceeds standing order limit and needs manager approval.",
    fullExplanation:
      "MedSupply Co invoice INV-88421 for $4,820 exceeds the $3,000 standing-order threshold for Indooroopilly. Two line items are new SKUs not on the approved catalogue.",
    category: "Approval",
    clinicId: "loc_indooroopilly",
    clinicName: "Indooroopilly",
    owner: "Alex Chen",
    requestedBy: "Priya Nair",
    priority: "High",
    status: "Awaiting Approval",
    createdAt: "2026-07-18T09:00:00.000Z",
    dueAt: "2026-07-20T17:00:00.000Z",
    requiredOutcome: "Approve, reject, or return for correction with reason.",
    decisionEffect: "Approved invoices release purchase order payment.",
    evidenceRequired: true,
    approvalPurpose: "Standing-order threshold overrun",
    unread: true,
    sourceRecord: "INV-88421",
    sourceModule: "Finance",
    attachments: [
      {
        id: "att-1",
        name: "INV-88421.pdf",
        sizeLabel: "248 KB",
        uploadedBy: "Priya Nair",
        uploadedAt: "2026-07-18T09:05:00.000Z",
      },
    ],
    relatedRecords: [
      { id: "rr-1", label: "Purchase Order PO-3310", module: "Finance", ref: "PO-3310" },
    ],
    approvalSteps: [
      {
        id: "as-1",
        order: 1,
        approver: "Alex Chen",
        status: "Pending",
      },
      {
        id: "as-2",
        order: 2,
        approver: "Jordan Blake",
        status: "Pending",
      },
    ],
    completionRequirements: ["Decision recorded", "Evidence reviewed"],
    comments: [
      {
        id: "c-1",
        author: "Priya Nair",
        body: "New gloves SKU substitutes discontinued stock. @Alex Chen please review.",
        at: "2026-07-18T09:10:00.000Z",
        mentions: ["Alex Chen"],
      },
    ],
    watchers: ["Jordan Blake"],
  }),

  base({
    id: "m2-exc-1",
    number: "ACT-2026-1048",
    title: "Staff document exception — expired WWCC",
    explanation: "Working with Children Check expired for a clinical staff member.",
    fullExplanation:
      "Expected: current WWCC on file. Actual: certificate expired 12 Jul 2026. Possible cause: renewal reminder missed during leave. Effect: roster eligibility blocked until evidence uploaded.",
    category: "Exception",
    clinicId: "loc_chapelhill",
    clinicName: "Chapel Hill",
    owner: "Alex Chen",
    requestedBy: "System",
    priority: "Urgent",
    status: "Open",
    createdAt: "2026-07-13T08:00:00.000Z",
    dueAt: "2026-07-15T17:00:00.000Z",
    requiredOutcome: "Acknowledge exception and obtain renewed evidence.",
    expectedResult: "Valid WWCC on HR file before roster publish.",
    actualResult: "WWCC expired 12 Jul 2026 — no renewal uploaded.",
    possibleCause: "Staff on leave; reminder not actioned.",
    possibleEffect: "Cannot roster clinical shifts until resolved.",
    recommendedNextAction: "Acknowledge, contact staff, upload renewal, request manager verification.",
    acknowledgementRequired: true,
    managerVerificationRequired: true,
    unread: true,
    escalationLevel: 2,
    sourceRecord: "HR-DOC-WWCC-441",
    sourceModule: "HR Documents",
    attachments: [
      {
        id: "att-2",
        name: "wwcc-expiry-notice.pdf",
        sizeLabel: "90 KB",
        uploadedBy: "System",
        uploadedAt: "2026-07-13T08:00:00.000Z",
      },
    ],
    relatedRecords: [
      { id: "rr-2", label: "Staff profile — Sam Ortega", module: "Staff", ref: "STF-882" },
    ],
    completionRequirements: ["Acknowledgement", "Resolution evidence", "Manager verification"],
  }),

  base({
    id: "m2-comp-1",
    number: "ACT-2026-1031",
    title: "Overdue compliance — cold chain log gap",
    explanation: "Two consecutive AM cold-chain readings missing for vaccine fridge.",
    fullExplanation:
      "Accreditation evidence requires twice-daily cold-chain readings. 18–19 Jul AM readings are missing for Fridge VF-02 at Bald Hills.",
    category: "Escalation",
    clinicId: "loc_baldhills",
    clinicName: "Bald Hills",
    owner: "Morgan Lee",
    requestedBy: "Compliance Centre",
    priority: "Urgent",
    status: "In Progress",
    createdAt: "2026-07-19T07:30:00.000Z",
    dueAt: "2026-07-19T12:00:00.000Z",
    requiredOutcome: "Investigate gap, document cause, verify fridge status.",
    expectedResult: "Complete AM/PM readings logged.",
    actualResult: "Two AM readings absent.",
    possibleCause: "Opening nurse delayed; checklist skipped.",
    possibleEffect: "Accreditation non-conformance risk.",
    recommendedNextAction: "Complete catch-up verification and escalate to clinic manager if vaccine risk.",
    unread: true,
    escalationLevel: 3,
    sourceRecord: "CC-LOG-VF02",
    sourceModule: "Compliance",
    watchers: ["Alex Chen"],
    completionRequirements: ["Investigation note", "Evidence attachment", "Manager verification"],
    comments: [
      {
        id: "c-2",
        author: "Morgan Lee",
        body: "Fridge currently in range. Investigating missed checklist steps.",
        at: "2026-07-19T10:00:00.000Z",
        mentions: [],
      },
    ],
  }),

  base({
    id: "m2-rem-1",
    number: "ACT-2026-1055",
    title: "Delegated reminder — fire drill briefing",
    explanation: "Reminder for quarterly fire drill briefing — delegated while owner on leave.",
    fullExplanation:
      "Quarterly fire drill briefing due this week. Original owner is on leave; delegated to Alex Chen with authority to complete.",
    category: "Reminder",
    clinicId: "loc_woolloongabba",
    clinicName: "Woolloongabba",
    owner: "Casey Wright",
    originalOwner: "Casey Wright",
    delegatedTo: "Alex Chen",
    delegatedByMe: false,
    delegationId: "del-1",
    requestedBy: "WHS Lead",
    priority: "Medium",
    status: "Open",
    createdAt: "2026-07-17T11:00:00.000Z",
    dueAt: "2026-07-21T09:00:00.000Z",
    requiredOutcome: "Confirm briefing scheduled or completed.",
    reminderType: "One-time",
    reminderAt: "2026-07-20T08:00:00.000Z",
    snoozeAllowed: true,
    unread: false,
    sourceRecord: "WHS-DRILL-Q3",
    sourceModule: "WHS",
    ownershipHistory: [
      {
        at: "2026-07-17T14:00:00.000Z",
        from: "Casey Wright",
        to: "Alex Chen",
        reason: "Owner on leave 17–24 Jul",
        kind: "delegate",
      },
    ],
  }),

  base({
    id: "m2-apr-2",
    number: "ACT-2026-1020",
    title: "Multi-step approval — roster publish Week 30",
    explanation: "Roster publish requires Practice Manager then Group Operations approval.",
    fullExplanation:
      "Week 30 roster for Chapel Hill includes overtime above policy threshold. Multi-step approval required before publish.",
    category: "Approval",
    clinicId: "loc_chapelhill",
    clinicName: "Chapel Hill",
    owner: "Alex Chen",
    requestedBy: "Riley Park",
    priority: "High",
    status: "Awaiting Approval",
    createdAt: "2026-07-16T15:00:00.000Z",
    dueAt: "2026-07-20T12:00:00.000Z",
    requiredOutcome: "Complete ordered approval pathway.",
    approvalPurpose: "Overtime threshold exception for roster publish",
    decisionEffect: "Publishes roster to staff app and payroll estimate.",
    evidenceRequired: true,
    unread: true,
    sourceRecord: "RST-W30-CH",
    sourceModule: "Rostering",
    approvalSteps: [
      {
        id: "as-3",
        order: 1,
        approver: "Alex Chen",
        status: "Approved",
        decidedAt: "2026-07-17T10:00:00.000Z",
        decisionNote: "Coverage justified by flu season demand.",
      },
      {
        id: "as-4",
        order: 2,
        approver: "Jordan Blake",
        status: "Pending",
      },
    ],
    attachments: [
      {
        id: "att-3",
        name: "roster-w30-overtime.xlsx",
        sizeLabel: "64 KB",
        uploadedBy: "Riley Park",
        uploadedAt: "2026-07-16T15:10:00.000Z",
      },
    ],
  }),

  base({
    id: "m2-esc-2",
    number: "ACT-2026-1060",
    title: "Urgent escalation — reception coverage gap tomorrow",
    explanation: "No reception cover confirmed for tomorrow AM at Lawnton.",
    fullExplanation:
      "Level 3 escalation: team leader notified after owner missed Level 1/2 reminders. Clinic opening at risk without reception cover.",
    category: "Escalation",
    clinicId: "loc_lawnton",
    clinicName: "Lawnton",
    owner: "Alex Chen",
    requestedBy: "Roster Engine",
    priority: "Urgent",
    status: "Open",
    createdAt: "2026-07-19T16:00:00.000Z",
    dueAt: "2026-07-20T08:00:00.000Z",
    requiredOutcome: "Confirm cover or adjust opening hours.",
    unread: true,
    escalationLevel: 3,
    sourceRecord: "RST-GAP-LAW-21JUL",
    sourceModule: "Rostering",
    recommendedNextAction: "Call casual bank or redistribute from nearby clinic.",
    watchers: ["Jordan Blake"],
  }),

  base({
    id: "m2-done-1",
    number: "ACT-2026-0988",
    title: "Completed — vaccine fridge probe calibration",
    explanation: "Calibration completed and verified by manager.",
    fullExplanation: "Annual probe calibration completed. Certificates filed. Manager verified.",
    category: "Exception",
    clinicId: "loc_forestlake",
    clinicName: "Forest Lake",
    owner: "Morgan Lee",
    requestedBy: "WHS Lead",
    priority: "Medium",
    status: "Completed",
    createdAt: "2026-07-01T09:00:00.000Z",
    dueAt: "2026-07-10T17:00:00.000Z",
    completedAt: "2026-07-09T14:20:00.000Z",
    requiredOutcome: "Calibrate and file certificate.",
    completionNote: "Probe calibrated by BioMed Services. Certificate uploaded.",
    outcome: "Resolved",
    managerVerificationRequired: true,
    verifiedAt: "2026-07-09T16:00:00.000Z",
    verifiedBy: "Alex Chen",
    unread: false,
    attachments: [
      {
        id: "att-4",
        name: "calibration-cert-july.pdf",
        sizeLabel: "120 KB",
        uploadedBy: "Morgan Lee",
        uploadedAt: "2026-07-09T14:15:00.000Z",
      },
    ],
  }),

  base({
    id: "m2-arch-1",
    number: "ACT-2026-0901",
    title: "Archived — Q2 fire extinguisher inspection",
    explanation: "Archived after demonstration retention period.",
    fullExplanation: "Q2 inspection completed, verified, and moved to archive after retention window.",
    category: "Reminder",
    clinicId: "loc_beachmere",
    clinicName: "Beachmere",
    owner: "Casey Wright",
    requestedBy: "WHS Lead",
    priority: "Low",
    status: "Archived",
    createdAt: "2026-04-02T09:00:00.000Z",
    dueAt: "2026-04-30T17:00:00.000Z",
    completedAt: "2026-04-28T11:00:00.000Z",
    archivedAt: "2026-06-28T11:00:00.000Z",
    requiredOutcome: "Complete inspection checklist.",
    completionNote: "All extinguishers passed.",
    outcome: "Completed",
    unread: false,
  }),

  base({
    id: "m2-conf-1",
    number: "ACT-2026-1070",
    title: "Confidential HR matter — access restricted",
    explanation: "Restricted content for authorised roles only.",
    fullExplanation:
      "Sensitive staff matter requiring Highly Confidential handling. Visible detail only for authorised managers.",
    category: "Approval",
    clinicId: "loc_eightmile",
    clinicName: "Eight Mile Plains",
    owner: "Jordan Blake",
    requestedBy: "HR Admin",
    priority: "High",
    status: "Awaiting Approval",
    sensitivity: "Highly Confidential",
    createdAt: "2026-07-19T12:00:00.000Z",
    dueAt: "2026-07-22T17:00:00.000Z",
    requiredOutcome: "Authorised decision only.",
    unread: true,
    approvalSteps: [
      { id: "as-5", order: 1, approver: "Jordan Blake", status: "Pending" },
    ],
  }),

  base({
    id: "m2-team-1",
    number: "ACT-2026-1051",
    title: "Exception — Best Practice sync mismatch",
    explanation: "Appointment counts differ between Best Practice and Pulse for yesterday.",
    fullExplanation:
      "Expected sync parity. Actual: 4 appointment variance. Routine exception may close after resolution note.",
    category: "Exception",
    clinicId: "loc_indooroopilly",
    clinicName: "Indooroopilly",
    owner: "Priya Nair",
    requestedBy: "System",
    priority: "Low",
    status: "Open",
    team: "Clinic Operations",
    createdAt: "2026-07-20T06:00:00.000Z",
    dueAt: "2026-07-22T17:00:00.000Z",
    requiredOutcome: "Reconcile variance and add resolution note.",
    expectedResult: "Matching appointment counts",
    actualResult: "4 appointment variance",
    acknowledgementRequired: false,
    managerVerificationRequired: false,
    unread: false,
    snoozeAllowed: true,
  }),

  base({
    id: "m2-watch-1",
    number: "ACT-2026-1040",
    title: "Reminder — accreditation evidence pack due",
    explanation: "Evidence pack assembly reminder for upcoming survey window.",
    fullExplanation: "Assemble standards evidence pack for Module C. Watching for progress.",
    category: "Reminder",
    clinicId: "loc_cannonhill",
    clinicName: "Cannon Hill",
    owner: "Riley Park",
    requestedBy: "Accreditation Lead",
    priority: "Medium",
    status: "Open",
    createdAt: "2026-07-14T10:00:00.000Z",
    dueAt: "2026-07-25T17:00:00.000Z",
    requiredOutcome: "Confirm pack readiness.",
    reminderType: "Repeating",
    repeatPattern: "Weekly",
    snoozeAllowed: true,
    unread: false,
    watchers: ["Alex Chen"],
    mandatoryReminder: false,
  }),

  base({
    id: "m2-del-by-me",
    number: "ACT-2026-1058",
    title: "Delegated by me — asset ticket follow-up",
    explanation: "You delegated this asset follow-up while covering another clinic.",
    fullExplanation: "Aircon service ticket follow-up delegated to Morgan Lee with updates to original owner.",
    category: "Reminder",
    clinicId: "loc_indooroopilly",
    clinicName: "Indooroopilly",
    owner: "Alex Chen",
    originalOwner: "Alex Chen",
    delegatedTo: "Morgan Lee",
    delegatedByMe: true,
    delegationId: "del-2",
    requestedBy: "Alex Chen",
    priority: "Medium",
    status: "In Progress",
    createdAt: "2026-07-18T13:00:00.000Z",
    dueAt: "2026-07-23T17:00:00.000Z",
    requiredOutcome: "Confirm contractor attendance.",
    unread: false,
    ownershipHistory: [
      {
        at: "2026-07-18T13:30:00.000Z",
        from: "Alex Chen",
        to: "Morgan Lee",
        reason: "Covering Cannon Hill this week",
        kind: "delegate",
      },
    ],
  }),
];

export const SEED_NOTIFICATIONS: InboxNotification[] = [
  {
    id: "n-1",
    title: "Approval required",
    reason: "Invoice exceeds standing order limit",
    actionId: "m2-inv-1",
    actionNumber: "ACT-2026-1042",
    clinicName: "Indooroopilly",
    at: "2026-07-18T09:12:00.000Z",
    priority: "High",
    read: false,
    kind: "mandatory-approval",
  },
  {
    id: "n-2",
    title: "Escalation Level 3",
    reason: "Reception coverage gap unresolved",
    actionId: "m2-esc-2",
    actionNumber: "ACT-2026-1060",
    clinicName: "Lawnton",
    at: "2026-07-19T18:00:00.000Z",
    priority: "Urgent",
    read: false,
    kind: "escalation",
  },
  {
    id: "n-3",
    title: "Exception opened",
    reason: "WWCC expired",
    actionId: "m2-exc-1",
    actionNumber: "ACT-2026-1048",
    clinicName: "Chapel Hill",
    at: "2026-07-13T08:01:00.000Z",
    priority: "Urgent",
    read: false,
    kind: "urgent",
  },
  {
    id: "n-4",
    title: "Routine sync notice",
    reason: "Best Practice sync completed with minor variance",
    actionId: "m2-team-1",
    actionNumber: "ACT-2026-1051",
    clinicName: "Indooroopilly",
    at: "2026-07-20T06:05:00.000Z",
    priority: "Low",
    read: false,
    kind: "routine",
    groupKey: "bp-sync",
  },
  {
    id: "n-5",
    title: "Routine sync notice",
    reason: "Best Practice sync completed with minor variance",
    actionId: "m2-team-1",
    actionNumber: "ACT-2026-1051",
    clinicName: "Indooroopilly",
    at: "2026-07-20T06:35:00.000Z",
    priority: "Low",
    read: false,
    kind: "routine",
    groupKey: "bp-sync",
  },
  {
    id: "n-6",
    title: "Mentioned in comment",
    reason: "Priya Nair mentioned you on invoice approval",
    actionId: "m2-inv-1",
    actionNumber: "ACT-2026-1042",
    clinicName: "Indooroopilly",
    at: "2026-07-18T09:10:00.000Z",
    priority: "Medium",
    read: true,
    kind: "routine",
  },
  {
    id: "n-7",
    title: "Delegation active",
    reason: "Casey Wright delegated fire drill reminder to you",
    actionId: "m2-rem-1",
    actionNumber: "ACT-2026-1055",
    clinicName: "Woolloongabba",
    at: "2026-07-17T14:00:00.000Z",
    priority: "Medium",
    read: true,
    kind: "routine",
  },
];

export const SEED_DELEGATIONS: DelegationRecord[] = [
  {
    id: "del-1",
    actionId: "m2-rem-1",
    fromOwner: "Casey Wright",
    delegate: "Alex Chen",
    startDate: "2026-07-17",
    endDate: "2026-07-24",
    reason: "Annual leave",
    canComplete: true,
    canFurtherDelegate: false,
    sendUpdatesToOwner: true,
    active: true,
  },
  {
    id: "del-2",
    actionId: "m2-del-by-me",
    fromOwner: "Alex Chen",
    delegate: "Morgan Lee",
    startDate: "2026-07-18",
    endDate: "2026-07-25",
    reason: "Covering Cannon Hill this week",
    canComplete: true,
    canFurtherDelegate: false,
    sendUpdatesToOwner: true,
    active: true,
  },
];

export const SEED_TEMPLATES: ActionTemplate[] = [
  {
    id: "tpl-sys-1",
    name: "Invoice approval",
    scope: "system",
    category: "Approval",
    description: "Standing-order / invoice threshold approval",
    defaults: {
      category: "Approval",
      priority: "High",
      actionType: "Approval",
    },
  },
  {
    id: "tpl-mgr-1",
    name: "Document expiry exception",
    scope: "manager",
    category: "Exception",
    description: "Manager-shared template for credential exceptions",
    defaults: {
      category: "Exception",
      priority: "Urgent",
      actionType: "Exception",
    },
  },
  {
    id: "tpl-pers-1",
    name: "My weekly WHS reminder",
    scope: "personal",
    category: "Reminder",
    description: "Personal template for WHS reminders",
    defaults: {
      category: "Reminder",
      priority: "Medium",
      actionType: "Reminder",
    },
  },
];

export const SEED_DRAFTS: ActionDraft[] = [
  {
    id: "draft-1",
    title: "Draft — supplier credit request",
    description: "Private draft for credit note follow-up",
    actionType: "Approval",
    category: "Approval",
    clinicId: "loc_indooroopilly",
    owner: "Alex Chen",
    priority: "Medium",
    dueAt: "2026-07-25T17:00:00.000Z",
    team: "Clinic Operations",
    requester: "Alex Chen",
    sensitivity: "Standard",
    sharedWith: [],
    isPrivate: true,
    updatedAt: T0,
    payload: {},
  },
];

export const SEED_SAVED_VIEWS: SavedView[] = [
  {
    id: "sv-1",
    name: "Due today — my clinics",
    scope: "private",
    pinned: true,
    createdBy: "Alex Chen",
    mainView: "my-actions",
    category: "all",
    filters: { ...DEFAULT_FILTERS, overdueOnly: false },
  },
  {
    id: "sv-2",
    name: "High risk escalations",
    scope: "shared",
    pinned: true,
    createdBy: "Jordan Blake",
    mainView: "all-clinics",
    category: "Escalation",
    filters: { ...DEFAULT_FILTERS, category: "Escalation", priority: "Urgent" },
  },
  {
    id: "sv-3",
    name: "Awaiting verification",
    scope: "private",
    pinned: false,
    createdBy: "Alex Chen",
    mainView: "all-clinics",
    category: "all",
    filters: { ...DEFAULT_FILTERS, awaitingVerification: true },
  },
];

export const SEED_AUDIT: AuditEntry[] = [
  {
    id: "aud-seed-1",
    actionId: "m2-inv-1",
    event: "Created",
    user: "Priya Nair",
    at: "2026-07-18T09:00:00.000Z",
    detail: "Invoice approval submitted",
  },
  {
    id: "aud-seed-2",
    actionId: "m2-exc-1",
    event: "Escalation started",
    user: "System",
    at: "2026-07-14T08:00:00.000Z",
    detail: "Level 2 — owner and team leader notified",
    newValue: "2",
  },
];

export const STAFF_DIRECTORY = [
  "Alex Chen",
  "Jordan Blake",
  "Morgan Lee",
  "Priya Nair",
  "Casey Wright",
  "Riley Park",
  "Sam Ortega",
  "Taylor Kim",
];

export const CLINIC_OPTIONS = [
  { id: "loc_woolloongabba", name: "Woolloongabba" },
  { id: "loc_baldhills", name: "Bald Hills" },
  { id: "loc_cannonhill", name: "Cannon Hill" },
  { id: "loc_eightmile", name: "Eight Mile Plains" },
  { id: "loc_chapelhill", name: "Chapel Hill" },
  { id: "loc_indooroopilly", name: "Indooroopilly" },
  { id: "loc_forestlake", name: "Forest Lake" },
  { id: "loc_lawnton", name: "Lawnton" },
  { id: "loc_beachmere", name: "Beachmere" },
];
